pageinfo = [[1522937757,0,0,0,null],
	[1538501792,0,0,0,null],
	[1521048070,0,0,0,null],
	[1523028160,0,0,0,null],
	[1523028160,0,0,0,null],
	[1522264793,0,0,0,null],
	[1522937757,0,0,0,null],
	[1538501792,0,0,0,null],
	[1523389323,0,0,0,null],
	[1523028160,0,0,0,null],
	[1602245205,0,0,0,null],
	[1522937757,0,0,0,null],
	[1602245281,0,0,0,null],
	[1518115010,0,0,0,null],
	[1519677710,0,0,0,null],
	[1519677710,0,0,0,null],
	[1522248134,0,0,0,null],
	[1516136672,0,0,0,null],
	[1601579551,0,0,0,null],
	[1601579551,0,0,0,null],
	[1522183320,0,0,0,null],
	[1522183320,0,0,0,null],
	[1516136672,0,0,0,null],
	[1601579551,0,0,0,null],
	[1519249125,0,0,0,null],
	[1519933760,0,0,0,null],
	[1522183320,0,0,0,null],
	[1601579551,0,0,0,null],
	[1519249125,0,0,0,null],
	[1523389323,0,0,0,null],
	[1522183320,0,0,0,null],
	[1520621508,0,0,0,null],
	[1519933760,0,0,0,null],
	[1602188015,0,0,0,null],
	[1516136672,0,0,0,null],
	[1601488112,0,0,0,null],
	[1602178894,0,0,0,null],
	[1601579551,0,0,0,null],
	[1602188028,0,0,0,null],
	[1516136672,0,0,0,null],
	[1523389323,0,0,0,null],
	[1601488112,0,0,0,null],
	[1602178894,0,0,0,null],
	[1522850045,0,0,0,null],
	[1522850045,0,0,0,null],
	[1522850045,0,0,0,null],
	[1522850045,0,0,0,null],
	[1523481300,0,0,0,null],
	[1522850045,0,0,0,null],
	[1522851475,0,0,0,null],
	[1522850045,0,0,0,null],
	[1522850045,0,0,0,null],
	[1522850045,0,0,0,null],
	[1522850045,0,0,0,null],
	[1523450651,0,0,0,null],
	[1522850045,0,0,0,null],
	[1522850045,0,0,0,null],
	[1523391412,0,0,0,null],
	[1524163236,0,0,0,null],
	[1524163236,0,0,0,null],
	[1524163236,0,0,0,null],
	[1602245361,0,0,0,null],
	[1524163236,0,0,0,null],
	[1524163236,0,0,0,null],
	[1531243406,0,0,0,null],
	[1524163236,0,0,0,null],
	[1524163236,0,0,0,null],
	[1523544126,0,0,0,null],
	[1522264793,0,0,0,null],
	[1522937757,0,0,0,null],
	[1523450373,0,0,0,null],
	[1522264793,0,0,0,null],
	[1520541217,0,0,0,null],
	[1523393724,0,0,0,null],
	[1601508057,0,0,0,null],
	[1602245791,0,0,0,null],
	[1523540439,0,0,0,null],
	[1602246054,0,0,0,null],
	[1521048070,0,0,0,null],
	[1602246328,0,0,0,null],
	[1602246391,0,0,0,null],
	[1516136672,0,0,0,null],
	[1602246469,0,0,0,null],
	[1528377667,0,0,0,null],
	[1521048070,0,0,0,null],
	[1601508057,0,0,0,null],
	[1523545265,0,0,0,null],
	[1538501792,0,0,0,null],
	[1535117404,0,0,0,null],
	[1523450373,0,0,0,null],
	[1602246699,0,0,0,null],
	[1519766358,0,0,0,null],
	[1522264793,0,0,0,null],
	[1523028160,0,0,0,null],
	[1538501792,0,0,0,null],
	[1520887725,0,0,0,null],
	[1522264793,0,0,0,null],
	[1523039925,0,0,0,null],
	[1523450373,0,0,0,null],
	[1602246777,0,0,0,null],
	[1516136672,0,0,0,null],
	[1516136672,0,0,0,null],
	[1516136672,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1587488391,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1587488042,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1580740365,0,0,0,null],
	[1522937757,0,0,0,null],
	[1602246890,0,0,0,null],
	[1523546479,0,0,0,null],
	[1535117404,0,0,0,null],
	[1602246943,0,0,0,null],
	[1521828329,0,0,0,null],
	[1523450373,0,0,0,null],
	[1520887725,0,0,0,null],
	[1523634044,0,0,0,null],
	[1523473465,0,0,0,null],
	[1516136672,0,0,0,null],
	[1520953315,0,0,0,null],
	[1523450373,0,0,0,null],
	[1523634044,0,0,0,null],
	[1523451041,0,0,0,null],
	[1523548123,0,0,0,null],
	[1520017473,0,0,0,null],
	[1520887725,0,0,0,null],
	[1523548504,0,0,0,null],
	[1522937757,0,0,0,null],
	[1523548800,0,0,0,null],
	[1535381496,0,0,0,null],
	[1602246984,0,0,0,null],
	[1523469254,0,0,0,null],
	[1520631174,0,0,0,null],
	[1516136672,0,0,0,null],
	[1538579975,0,0,0,null],
	[1523450275,0,0,0,null],
	[1522939877,0,0,0,null],
	[1522246608,0,0,0,null],
	[1522246608,0,0,0,null],
	[1518721675,0,0,0,null],
	[1522246608,0,0,0,null],
	[1522246608,0,0,0,null],
	[1518721675,0,0,0,null],
	[1518721675,0,0,0,null],
	[1522246608,0,0,0,null],
	[1522246608,0,0,0,null],
	[1518721675,0,0,0,null],
	[1518721675,0,0,0,null],
	[1601579551,0,0,0,null],
	[1522246608,0,0,0,null],
	[1522246608,0,0,0,null],
	[1518721675,0,0,0,null],
	[1518721675,0,0,0,null],
	[1601579551,0,0,0,null],
	[1522246608,0,0,0,null],
	[1602109883,0,0,0,null],
	[1602109883,0,0,0,null],
	[1518721675,0,0,0,null],
	[1602109883,0,0,0,null],
	[1518721675,0,0,0,null],
	[1518721675,0,0,0,null],
	[1522246608,0,0,0,null],
	[1602247134,0,0,0,null],
	[1522246608,0,0,0,null],
	[1522246608,0,0,0,null],
	[1522246608,0,0,0,null],
	[1522246608,0,0,0,null],
	[1522761312,0,0,0,null],
	[1523477324,0,0,0,null],
	[1522246608,0,0,0,null],
	[1601579551,0,0,0,null],
	[1522246608,0,0,0,null],
	[1602109883,0,0,0,null],
	[1518721675,0,0,0,null],
	[1522162614,0,0,0,null],
	[1602247193,0,0,0,null],
	[1602109883,0,0,0,null],
	[1522246608,0,0,0,null],
	[1522849484,0,0,0,null],
	[1522849484,0,0,0,null],
	[1522849484,0,0,0,null],
	[1522849484,0,0,0,null],
	[1522851812,0,0,0,null],
	[1522849484,0,0,0,null],
	[1522849484,0,0,0,null],
	[1522849484,0,0,0,null],
	[1522849484,0,0,0,null],
	[1522849484,0,0,0,null],
	[1522849484,0,0,0,null],
	[1522849484,0,0,0,null],
	[1522849484,0,0,0,null],
	[1522849484,0,0,0,null],
	[1522849484,0,0,0,null],
	[1522849484,0,0,0,null],
	[1522849484,0,0,0,null],
	[1522849484,0,0,0,null],
	[1522849484,0,0,0,null],
	[1522849484,0,0,0,null],
	[1522849484,0,0,0,null],
	[1522849484,0,0,0,null],
	[1522849484,0,0,0,null],
	[1522849484,0,0,0,null],
	[1522849484,0,0,0,null],
	[1521033384,0,0,0,null],
	[1535390315,0,0,0,null],
	[1602247301,0,0,0,null],
	[1520887725,0,0,0,null],
	[1519852838,0,0,0,null],
	[1523554695,0,0,0,null],
	[1535372140,0,0,0,null],
	[1535372378,0,0,0,null],
	[1531234314,0,0,0,null],
	[1529441834,0,0,0,null],
	[1519852838,0,0,0,null],
	[1519852838,0,0,0,null],
	[1520887725,0,0,0,null],
	[1602247376,0,0,0,null],
	[1602247430,0,0,0,null],
	[1602247747,0,0,0,null],
	[1602247831,0,0,0,null],
	[1523478177,0,0,0,null],
	[1602247873,0,0,0,null],
	[1602247927,0,0,0,null],
	[1519739826,0,0,0,null],
	[1601579551,0,0,0,null],
	[1523469272,0,0,0,null],
	[1522939877,0,0,0,null],
	[1516136672,0,0,0,null],
	[1521836301,0,0,0,null],
	[1602178894,0,0,0,null],
	[1516136672,0,0,0,null]];
pagedata = [ ["../CommsProtocol/Ethernet/EthernetDwgs.html","Ethernet - Drawings","Ethernet Engineering Drawings The following table contains links to the MDS engineering drawings for the Ethernet System: Drawing Number Drawing T...",""],
["../CommsProtocol/Ethernet/EthernetOverview.html","Ethernet - Overview","Ethernet Overview Ethernet (IEEE 802.3 standard) is a link layer protocol in the TCP/IP stack which describes how networked devices communicate by...",""],
["../CommsProtocol/Ethernet/EthernetVDocs.html","Ethernet - Vendor Docs","Ethernet Vendor Documentation The following table contains links to vendor documentation for components used in the Ethernet System: Manufacturer ...",""],
["../CommsProtocol/Ethernet/RTNetwork.html","Ethernet - Real-Time Network","Real-Time Network Overview The network diagram below displays an overview of the proDAS Real-Time Network configuration. During a test, the PLC is...",""],
["../CommsProtocol/Ethernet/UserNetwork.html","Ethernet - User Network","User Network Overview The network diagram below displays an overview of the proDAS User Network configuration. User Network Block Diagram For more...",""],
["../CommsProtocol/IRIGB/IRIGBComp.html","IRIG-B - Components","IRIG-B Components The IRIG-B System contains the following major components: Component Description GPS IRIG-B Receiver Card The GPS IRIG-B Receive...",""],
["../CommsProtocol/IRIGB/IRIGBDwgs.html","IRIG-B - Drawings","IRIG-B Engineering Drawings The following table contains links to the MDS engineering drawings for the IRIG-B System: Drawing Number Drawing Title...",""],
["../CommsProtocol/IRIGB/IRIGBOverview.html","IRIG-B - Overview","IRIG-B Overview Inter-Range Instrumentation Group time codes, commonly known as IRIG time codes, are standard formats for transferring timing info...",""],
["../CommsProtocol/IRIGB/IRIGBRSPL.html","IRIG-B - RSPL","IRIG-B Recommended Spare Parts List The following table lists the MDS recommended spare parts for the IRIG-B System: Manufacturer Quantity Part Nu...",""],
["../CommsProtocol/IRIGB/IRIGBVDocs.html","IRIG-B - Vendor Docs","IRIG-B Vendor Documentation The following table contains links to vendor documentation for components used in the IRIG-B System: Manufacturer Manu...",""],
["../CommsProtocol/M1553PCI/M1553PCIComp.html","M1553 PCI System - Components","M1553 PCI System Components The M1553 PCI System contains the following major components: Component Description Ballard Omnibus PCI M1553 Interfac...",""],
["../CommsProtocol/M1553PCI/M1553PCIDwgs.html","M1553 PCI System - Drawings","M1553 PCI System Engineering Drawings The following table contains links to the MDS engineering drawings for the M1553 PCI System: Drawing Number ...",""],
["../CommsProtocol/M1553PCI/M1553PCIOper.html","M1553 PCI System - Operation","M1553 PCI System Operation The M1553 PCI System provides a means of receiving and transmitting electronic information between the Electronic Engin...",""],
["../CommsProtocol/M1553PCI/M1553PCIOverview.html","M1553 PCI System - Overview","M1553 PCI System Overview MIL-STD-1553 is a military standard published by the United States Department of Defense that defines the mechanical, el...",""],
["../CommsProtocol/M1553PCI/M1553PCIRSPL.html","M1553 PCI System - RSPL","M1553 PCI System Recommended Spare Parts List The following table lists the MDS recommended spare parts for the M1553 PCI System: Manufacturer Qua...",""],
["../CommsProtocol/M1553PCI/M1553PCIVDocs.html","M1553 - Vendor Docs","M1553 PCI System Vendor Documentation The following table contains links to vendor documentation for components used in the M1553 PCI System: Manu...",""],
["../CompCfg/DataBR/BackUpSchedule.html","Data Backup &#38; Recovery - Backup Schedule","Data Backup &#38; Recovery Facility Computers Backup Schedule The table below outlines the scheduled back-up times for the facility computers. Compute...",""],
["../CompCfg/DataBR/DataBROperL.html","Linux Data Backup &#38; Recovery - Operation","Linux Data Backup &#38; Recovery Operation MDS recommends reviewing the backup log files weekly to verify successful completion of the backup operatio...",""],
["../CompCfg/DataBR/DataBROperW.html","Data Backup &#38; Recovery - Windows PCs","Data Backup &#38; Recovery Operation Windows Data Backup and Recovery Strategy MDS recommends reviewing the backup log files weekly to verify successf...",""],
["../CompCfg/DataBR/DataBRVDocs.html","Data Backup &#38; Recovery - Vendor Docs","Data Backup &#38; Recovery Vendor Documentation The following table contains links to vendor documentation for Data Backup &#38; Recovery: Manufacturer Ma...",""],
["../CompCfg/DataBR/LinuxDataBROver.html","Data Backup &#38; Recovery for Linux Host Computer","Data Backup &#38; Recovery for Linux Host Computer Overview Proper data backup is key to preventing loss of information and reducing facility down-tim...",""],
["../CompCfg/DataBR/WindowsDataBROver.html","Data Backup &#38; Recovery for Windows Based Computers","Data Backup &#38; Recovery for Windows Based Computers Overview Proper data backup is key to preventing loss of information and reducing facility down...",""],
["../CompCfg/GeneralInfo/PCFileSystem.html","Windows-based Computers - File System Org","Windows-based Computers File System Organisation The proDAS software is centrally located in a root proDAS directory. This directory can be stored...",""],
["../CompCfg/GeneralInfo/PCMaint.html","Computers - Maintenance","Windows Computers Maintenance To avoid electric shock, disconnect power from the computer until the dusting and visual inspection are completed. E...",""],
["../CompCfg/HostPC/HostPCFS.html","Host Computer - File System Org","Host Computer File System Organisation The Host Computer hard disks are configured with three basic partitions, including: the root partition for ...",""],
["../CompCfg/HostPC/HostPCHW.html","Linux Host Computer - Hardware Components","Host Computer Hardware Components The following table identifies the hardware components that are installed on the Host Computer: Component Descri...",""],
["../CompCfg/HostPC/HostPCMaint.html","Host Computer - Maintenance","Host Computer Maintenance To avoid electric shock, disconnect power from the computer until the dusting and visual inspection are completed. Elect...",""],
["../CompCfg/HostPC/HostPCOper.html","Host Computer - Operation","Host Computer Operation The Host Computer runs a Real-Time multi-tasking Linux operating system which allows task priorities to be set in parallel...",""],
["../CompCfg/HostPC/HostPCOverview.html","Host Computer - Overview","Host Computer Overview The Host Computer runs a Real-Time multi-tasking Linux operating system which allows task priorities to be set in parallel,...",""],
["../CompCfg/HostPC/HostPCRSPL.html","Host Computer - RSPL","Host Computer Recommended Spare Parts List The following table lists the MDS recommended spare parts for the Host Computer: Manufacturer Quantity ...",""],
["../CompCfg/HostPC/HostPCSW.html","Linux Host Computer - Software Components","Host Computer Software Components The Host Computer is backed-up using Acronis True Image Echo Server for Linux software. For details, see Data Ba...",""],
["../CompCfg/HostPC/HostPCVDocs.html","Linux Host Computer - Vendor Docs","Host Computer Vendor Documentation The following table contains links to vendor documentation for the Host Computer: Manufacturer Manual Title Man...",""],
["../CompCfg/MgmtPC/MgmtPCHW.html","Management GUI Computer - Hardware Components","Management GUI Computer Hardware Components The following table identifies the hardware components that are installed on the Management GUI Comput...",""],
["../CompCfg/MgmtPC/MgmtPCOper.html","Management GUI Computer - Operation","Management GUI Computer Operation The Management GUI Computer provides a graphical user interface to proDAS. The Management GUI Computer is instal...",""],
["../CompCfg/MgmtPC/MgmtPCOverview.html","Management GUI Computer - Overview","Management GUI Computer Overview The Management GUI Computer (also referred to as Management Graphical User Interface Computer) is a PC-based comp...",""],
["../CompCfg/MgmtPC/MgmtPCSW.html","Management GUI Computer - Software Components","Management GUI Computer Software Components The following table identifies the software components that are installed on the Management GUI Comput...",""],
["../CompCfg/MgmtPC/MgmtPCVDocs.html","Management GUI Computer - Vendor Documentation","Management GUI Computer Vendor Documentation The following table contains links to vendor documentation for the Management GUI Computer: Manufactu...",""],
["../CompCfg/RTDPC/RTDPCHW.html","Real-Time Display Computer - Hardware Components","Real-Time Display Computer Hardware Components There are four Real-Time Display (RTD) computers in Test Cell 25. There are (11) monitors connected...",""],
["../CompCfg/RTDPC/RTDPCOper.html","Real-Time Display Computer - Operation","Real-Time Display Computer Operation The Real-Time Display (RTD) Computer displays real-time data, such as engine test parameters. There are 4 RTD...",""],
["../CompCfg/RTDPC/RTDPCOverview.html","Real-Time Display Computer - Overview","Real-Time Display Computer Overview The Real-Time Display (RTD) Computer displays real-time data, such as engine test parameters. The RTD Computer...",""],
["../CompCfg/RTDPC/RTDPCRSPL.html","Real-Time Display Computer - RSPL","Real-Time Display Computer Recommended Spare Parts List The following table lists the MDS recommended spare parts for the Real-Time Display Comput...",""],
["../CompCfg/RTDPC/RTDPCSW.html","Real-Time Display Computer - Software Components","Real-Time Display Computer Software Components The following table identifies the software components that are installed on the Real-Time Display ...",""],
["../CompCfg/RTDPC/RTDPCVDocs.html","Real-Time Display Computer - Vendor Documentation","Real-Time Display Computer Vendor Documentation The following table contains links to vendor documentation for components used in the Real-Time Di...",""],
["../ControlMonitor/UECU/UECUActuator.html","Throttle - Actuator","Throttle Actuator An actuator is typically included with systems that have engines that require electromechanical fuel control. The actuator consi...",""],
["../ControlMonitor/UECU/UECUComp.html","Throttle - Components","Throttle Throttle System Components The Throttle System contains the following major components: Component Description Throttle Quadrant The throt...",""],
["../ControlMonitor/UECU/UECUController.html","Throttle - Controller","Throttle Throttle Controller The throttle controller contains an Allen-Bradley ControlLogix PLC with discrete and analogue input/output modules, w...",""],
["../ControlMonitor/UECU/UECUDisplay.html","Throttle - Display Computer Screens","Throttle Display Computer Screens The display computer screens are described in the section below. The display computer screens are divided into t...",""],
["../ControlMonitor/UECU/UECUDwgs.html","Throttle - Drawings","Throttle Engineering Drawings The following table contains links to the MDS engineering drawings for the Throttle System: Drawing Number Drawing T...",""],
["../ControlMonitor/UECU/UECUHW.html","Throttle - Computer Hardware","Throttle Touchscreen Display Computer Hardware Components Touchscreen Display Computer contains the following hardware components: Component Descr...",""],
["../ControlMonitor/UECU/UECUMaint.html","Throttle - Maintenance","Throttle Maintenance The Throttle components are under power. To avoid personal injury or damage to equipment, disconnect power from the Throttle ...",""],
["../ControlMonitor/UECU/UECUOper.html","Throttle - Operation","Throttle Operation The Throttle System allows an operator to accurately control the fuel supply to a test engine. The Throttle System can be run i...",""],
["../ControlMonitor/UECU/UECUOverview.html","Throttle - Overview","Throttle Overview The Universal Engine Command Unit (UECU-500 Mark III) (also know as the Throttle System) is a modular throttle actuation system ...",""],
["../ControlMonitor/UECU/UECUQuadrant.html","Throttle - Quadrant","Throttle Throttle Quadrant The throttle quadrant is the user interface to the engine fuel control system. The throttle quadrant is a throttle leve...",""],
["../ControlMonitor/UECU/UECUResolver.html","Throttle - Resolver Chassis","Throttle Resolver Chassis resolvers are typically included with systems that have engines equipped with electronic fuel control. The resolver chas...",""],
["../ControlMonitor/UECU/UECURSPL.html","Throttle - RSPL","Throttle Recommended Spare Parts List The following table lists the MDS recommended spare parts for the Throttle: Manufacturer Quantity Part Numbe...",""],
["../ControlMonitor/UECU/UECURVDT.html","Throttle - RVDT Chassis","Throttle RVDT Chassis Typically RVDT&#39;s are included with systems that have engines equipped with electronic fuel control. The RVDT chassis is a 19...",""],
["../ControlMonitor/UECU/UECUSW.html","Throttle - Computer Software","Throttle Touchscreen Display Computer Software Components The following table identifies the software components that are installed on the touchsc...",""],
["../ControlMonitor/UECU/UECUVDocs.html","Throttle - Vendor Docs","Throttle Vendor Documentation The following table contains links to vendor documentation for components used in the Throttle System: Manufacturer ...",""],
["../DynamicSystems/DDS-MullerBBM/DDSComp.html","DDS - Components","Dynamic Data System (DDS) - Muller-BBM PAK MKII Components The Dynamic Data System (DDS) - Muller-BBM PAK MKII contains the following major compon...",""],
["../DynamicSystems/DDS-MullerBBM/DDSDwgs.html","DDS - Drawings","Dynamic Data System (DDS) - Muller-BBM PAK MKII Engineering Drawings The following table contains the MDS engineering drawings for the Dynamic Dat...",""],
["../DynamicSystems/DDS-MullerBBM/DDSMaint.html","DDS - Maintenance","Dynamic Data System (DDS) - Muller-BBM PAK MKII Maintenance To avoid electric shock, disconnect power from the PAK MKII Mainframe until the dustin...",""],
["../DynamicSystems/DDS-MullerBBM/DDSOper.html","DDS - Operation","Dynamic Data System (DDS) - Muller-BBM PAK MKII Operation The Dynamic Data System (DDS) is a Muller-BBM PAK MKII Data Acquisition System (referred...",""],
["../DynamicSystems/DDS-MullerBBM/DDSOverview.html","DDS - Overview","Dynamic Data System (DDS) - Muller-BBM PAK MKII Overview The Dynamic Data System (DDS) is used to collect engine data that requires high sampling ...",""],
["../DynamicSystems/DDS-MullerBBM/DDSRSPL.html","DDS - RSPL","Dynamic Data System (DDS) - Muller-BBM PAK MKII Recommended Spare Parts List The following table lists the MDS recommended spares for the Dynamic ...",""],
["../DynamicSystems/DDS-MullerBBM/DDSVDocs.html","DDS - Vendor Documentation","Dynamic Data System (DDS) - Muller-BBM PAK MKII Vendor Documentation The following table contains the vendor documentation for the Dynamic Data Sy...",""],
["../DynamicSystems/DDS-MullerBBM/ModbusSW.html","DDS - Components - Modbus2PAK Software","Dynamic Data System (DDS) - Muller-BBM PAK MKII ModBus2PAK Software The Modbus2PAK software is the main communication interface between the proDAS...",""],
["../DynamicSystems/DDS-MullerBBM/PAKAnalyzer.html","DDS - Components - PAK Embedded Analyzer","Dynamic Data System (DDS) - Muller-BBM PAK MKII PAK Embedded Analyzer The PAK Embedded Analyzer is the main communication interface between the pr...",""],
["../Facility/UPS/10KVAUPS.html","Components - 10 KVA UPS","Uninterruptible Power Supply (UPS) 10 KVA UPS The 10 KVA UPS is a UPS-Teknik KR31 (3p-1p) Series 10-20 KVA UPS. The UPS unit provides a 10 KVA sus...",""],
["../Facility/UPS/UPSComp.html","Uninterruptible Power Supply (UPS) - Components","Uninterruptible Power Supply (UPS) Components The Uninterruptible Power Supply (UPS) System contains the following major components: Component Des...",""],
["../Facility/UPS/UPSDwgs.html","UPS - Drawings","Uninterruptible Power Supply (UPS) Engineering Drawings The following table contains links to the MDS engineering drawings for the Uninterruptible...",""],
["../Facility/UPS/UPSMaint.html","UPS - Maintenance","Uninterruptible Power Supply (UPS) Maintenance The UPS contains lethal high voltage. Removal by unqualified personnel of the doors of the UPS can ...",""],
["../Facility/UPS/UPSOper.html","UPS - Operation","Uninterruptible Power Supply (UPS) Operation Facility emergency battery back-up power is supplied by the following UPS units: 10 KVA UPS The UPS u...",""],
["../Facility/UPS/UPSOverview.html","UPS - Overview","Uninterruptible Power Supply (UPS) Overview The Uninterruptible Power Supply (UPS) provides emergency battery back-up power for data systems and f...",""],
["../Facility/UPS/UPSVDocs.html","UPS","Uninterruptible Power Supply (UPS) Vendor Documentation The following table contains links to vendor documentation for components used in the Unin...",""],
["../Home/Home.html","GKN Aerospace Test Cell 25","GKN Aerospace Test Cell 25 Overview The Indoor Aero Engine Test Facility at the Trollhattan test site located in Trollhattan, Sweden is designed t...",""],
["../Home/proDAS/proDASCfgTools.html","Your proDAS - Configuration Tools","Your proDAS Configuration Tools Your proDAS system is configured for the following Configuration Tools: Instrumentation Post Test Functions Availa...",""],
["../Home/proDAS/proDASCustomApps.html","Your proDAS - Custom Applications","Your proDAS Custom Applications Your proDAS system is configured for the following Custom Applications: proDAS Custom Applications Available ARINC...",""],
["../Home/proDAS/proDASHwSubSys.html","Your proDAS - Hardware Subsystems","Your proDAS Hardware Subsystems Your proDAS system is configured for the following Hardware Subsystems: proDAS Hardware Subsystems Available AFDX ...",""],
["../Home/proDAS/proDASHwSystem.html","Your proDAS - Hardware Systems","Your proDAS proDAS Hardware Systems Your proDAS system is configured for the following Hardware Systems: proDAS Hardware Systems Analogue Inputs D...",""],
["../Home/proDAS/proDASInstPostT.html","Your proDAS - Instrumentation Post Test Functions","Your proDAS Instrumentation Post Test Functions Your proDAS system is configured for the following Instrumentation Post Test Functions: Instrument...",""],
["../Home/proDAS/proDASInstPreT.html","Your proDAS - Instrumentation Pre Test Functions","Your proDAS Instrumentation Pre Test Functions Your proDAS system is configured for the following Instrumentation Pre Test Functions: Instrumentat...",""],
["../Home/proDAS/proDASOper.html","Your proDAS - Operation","Your proDAS Operation The operational information is contained in the How To section. How To The following table contains links to instructional i...",""],
["../Home/proDAS/proDASSysOver.html","Your proDAS - System Overview","Your proDAS Overview The proDAS documentation is presented in a generic manner to encompass all aspects of the software. Sections within the proDA...",""],
["../Home/Start/StartOper.html","Getting Started - Using MDS PSM","Getting Started Using the MDS Product Support Manual The MDS Product Support Manual (MDS PSM) is the user&#39;s primary source of reference informatio...",""],
["../Home/Start/StartOverview.html","Getting Started","Getting Started Overview The MDS Product Support Manual (MDS PSM) is an on-line web based user friendly technical package offering concise and inf...",""],
["../index.html","D-0000278 - PSM, GKN Aerospace, Trollhattan Test Cell 25","D-0000278 - PSM, GKN Aerospace, Trollhattan Test Cell 25 Release 02 October 2020 Home Getting Started Overview Using the MDS PSM Your proDAS Overv...",""],
["../Measurement/PneuPMeas/9116Scanner.html","Components - 9216 Pneumatic Intelligent Pressure Scanner","Pneumatic Pressure Measurement 9216 Pneumatic Intelligent Pressure Scanners The NetScanner Model 9216 is a 16 channel Pneumatic Intelligent pressu...",""],
["../Measurement/PneuPMeas/PneuPMComp.html","Pneumatic Pressure Measurement - Components","Pneumatic Pressure Measurement Components The Pneumatic Pressure Measurement System contains the following major components: Component Description...",""],
["../Measurement/PneuPMeas/PneuPMDwgs.html","Pneumatic Pressure Measurement - Drawings","Pneumatic Pressure Measurement Engineering Drawings The following table contains links to the MDS engineering drawings for the Pneumatic Pressure ...",""],
["../Measurement/PneuPMeas/PneuPMMaint.html","Pneumatic Pressure Measurement - Maintenance","Pneumatic Pressure Measurement Maintenance The Pneumatic Pressure Measurement system operates at high pressures. To prevent serious injury and/or ...",""],
["../Measurement/PneuPMeas/PneuPMOper.html","Pneumatic Pressure Measurement - Operation","Pneumatic Pressure Measurement Operation The Pneumatic Pressure Measurement System measures the following pressures: engine and facility air press...",""],
["../Measurement/PneuPMeas/PneuPMOverview.html","Pneumatic Pressure Measurement - Overview","Pneumatic Pressure Measurement Overview The Pneumatic Pressure Measurement system measures engine and test facility pressures. The system can cons...",""],
["../Measurement/PneuPMeas/PneuPMRSPL.html","Pneumatic Pressure Measurement - RSPL","Pneumatic Pressure Measurement Recommended Spare Parts List The following table lists the MDS recommended spare parts for the Pneumatic Pressure M...",""],
["../Measurement/PneuPMeas/PneuPMVDocs.html","Pneumatic Pressure Measurement - Vendor Docs","Pneumatic Pressure Measurement Vendor Documentation The following table contains links to vendor documentation for components used in the Pneumati...",""],
["../Measurement/TempMeas/DTS3250Scanner.html","Temperature Measurement - Components - DTS3250 Scanners","Temperature Measurement System Scanivalve DTS3250/DTS4050 Only v3.4.3 or higher of the proDAS software has the ability to configure and acquire da...",""],
["../Measurement/TempMeas/EX1048Scanner.html","Temperature Measurement - Components - EX1048A Scanners","Temperature Measurement System EX1048A Temperature Scanners There are four VTI Instruments 48 Channel Precision Thermocouple Instruments installed...",""],
["../Measurement/TempMeas/TempMsComp.html","Temperature Measurement - Components","Temperature Measurement System Components The Temperature Measurement System contains the following major components: Component Description DTS325...",""],
["../Measurement/TempMeas/TempMsDwgs.html","Temperature Measurement - Drawings","Temperature Measurement System Engineering Drawings The following table contains links to the MDS engineering drawings for the Temperature Measure...",""],
["../Measurement/TempMeas/TempMsMaint.html","Temperature Measurement - Maintenance","Temperature Measurement System Maintenance To prevent serious injury and or irreparable damage to equipment, MDS advises that an Energy Isolation ...",""],
["../Measurement/TempMeas/TempMsOper.html","Temperature Measurement - Operation","Temperature Measurement System Operation The Temperature Measurement System uses 192 channels that are scanned at up to 100 times per second (50 h...",""],
["../Measurement/TempMeas/TempMsOverview.html","Temperature Measurement","Temperature Measurement System Overview The Temperature Measurement System measures test article and test facility temperatures. Typically the sys...",""],
["../Measurement/TempMeas/TempMsRSPL.html","Temperature Measurement - RSPL","Temperature Measurement System Recommended Spare Parts List The following table lists the MDS recommended spare parts for the Temperature Measurem...",""],
["../Measurement/TempMeas/TempMsVDocs.html","Temperature Measurement - Vendor Docs","Temperature Measurement System Vendor Documentation The following table contains links to vendor documentation for components used in the Temperat...",""],
["../proDASHelp/CustomApps/ACI/ACI.htm","Automated CITS Import into proDAS (Option*)","Automated CITS Import into proDAS (Option*) Overview The Automated CITS Import into proDAS (ACI) utility converts CITS configuration files into th...",""],
["../proDASHelp/CustomApps/ArincChanList/ArincChanList.htm","ARINC Channel List (Option*)","ARINC Channel List (Option*) Overview The ARINC Display shows the ARINC information being transmitted to and received from the EEC (Electronic Eng...",""],
["../proDASHelp/CustomApps/CCS/CCS.html","CCS Messaging System (Option*)","CCS Messaging System (Option*) Overview The CCS Messaging System is used to exchange messages between proDAS and the CCS (client-supplied). This a...",""],
["../proDASHelp/CustomApps/CDR/CDR.html","Calibration Data Retrieval (CDR) Utility (Option*)","Calibration Data Retrieval (CDR) Utility (Option*) Overview The Calibration Data Retrieval (CDR) Utility retrieves data from the RAMS remote calib...",""],
["../proDASHelp/CustomApps/CDS/CDS.htm","Calibration Data Sync (CDS) Utility (Option*)","Calibration Data Sync (CDS) Utility (Option*) Overview The Calibration Data Sync (CDS) Utility synchronizes calibration data tables in the local p...",""],
["../proDASHelp/CustomApps/CIE/CIE.htm","Configuration Import / Export (CIE) Utility (Option*)","Configuration Import / Export (CIE) Utility (Option*) Overview The Configuration Import / Export (CIE) Utility allows the user to import Rolls-Roy...",""],
["../proDASHelp/CustomApps/CUTI/CUTI.htm","Configure User Test Information (Option*)","Configure User Test Information (Option*) Overview Configuration User Test Information (CUTI) is a single step method of configuring proDAS (inclu...",""],
["../proDASHelp/CustomApps/DCU/DCU.htm","Data Conversion Utility (DCU)","Data Conversion Utility (DCU) (Option*) Overview The Data Conversion Utility (DCU) is a Windows based console application which converts Steady-St...",""],
["../proDASHelp/CustomApps/Easifit/Easifit.html","EASIFIT","EASIFIT (Option*) Overview EASIFIT is a specific file format that is designed to interface with the Rolls-Royce on-line data analysis programs whi...",""],
["../proDASHelp/CustomApps/ExtHookFramework/ExtHookFramework.htm","External Hook Framework (Option*)","External Hook Framework (Option*) Overview The External Hook Framework allows the user to easily read and write channel values from and to the pro...",""],
["../proDASHelp/CustomApps/InstrumentControls/InstrumentControls.htm","Instrument Controls (Option*)","Instrument Controls (Option*) Overview Accessed from the Management GUI Tools menu, the proDAS Instrument Controls have been divided into the foll...",""],
["../proDASHelp/CustomApps/MDSThrustCalUtility/MDSThrustCalUtility.htm","MDS Thrust Calibration Utility (*Option)","MDS Thrust Calibration Utility (*Option) Overview The MDS Thrust Calibration Utility provides test cell personnel with the ability to calibrate th...",""],
["../proDASHelp/CustomApps/OMS/OMS.htm","Onboard Maintenance System (Option*)","Onboard Maintenance System (Option*) Overview The Onboard Maintenance System (OMS) is part of the proDAS ARINC System used to test the FADEC on th...",""],
["../proDASHelp/CustomApps/REMS/REMS.html","REMS External Hook Application (Option*)","Richmond Emission Measurement System (REMS) External Hook Application (Option*) Overview The Richmond Emission Measurement System (REMS) External ...",""],
["../proDASHelp/CustomApps/RuleEditor/RuleEditor.htm","Rule Editor (Option*)","Rule Editor (Option*) Overview The Rule Editor is a stand-alone application designed to create and edit rules to be used later in the Automated CI...",""],
["../proDASHelp/CustomApps/SnecmaXML/SnecmaXML.htm","Snecma XML Transfer (Option*)","Snecma XML Transfer (Option*) Overview The Snecma XML Transfer (SNEXML) application translates steady-state (fullset) and transient (history and c...",""],
["../proDASHelp/CustomApps/TCA/TCA.htm","Thrust Calibration Application (TCA)","Thrust Calibration Application (TCA) (Option*) Overview The Thrust Calibration Application (TCA) is a component of the Thrust Calibration and Thru...",""],
["../proDASHelp/CustomApps/TOCEUM/TOCEUM.htm","TOCEUM (Option*)","TOCEUM (Option*) Overview The TOC and EUM is an External Hook program that monitors the state of the engine and records statistics, on the life us...",""],
["../proDASHelp/CustomApps/TrimBalance/TrimBalance.htm","Engine Trim Balance","Engine Trim Balance (Option*) Overview The Trim Balance system is used in conjunction with the CEC Vibration Monitoring System that addresses engi...",""],
["../proDASHelp/CustomApps/WeatherStation/WeatherStation.htm","Weather Station (WS) Subsystem","Weather Station (WS) Subsystem (Option*) Overview The Weather Station (WS) Subsystem is a proDAS external hook program connected to a MET3A/MET4A ...",""],
["../proDASHelp/DASConfigTools/BPTableEditor/BPTableEditor.htm","Break Point Table Editor","Break Point Table Editor Overview The Break Point Table Editor is used to create and edit break point tables. Only break point tables used for cal...",""],
["../proDASHelp/DASConfigTools/DisplayPages/DisplayPages.htm","Creating and Modifying Display Pages","Creating and Modifying Display Pages Overview Display pages are created, administrated and modified by the RTD Editor and displayed in the RTD Dri...",""],
["../proDASHelp/DASConfigTools/EUEditor/EUEditor.htm","Engineering Unit Editor","Engineering Unit Editor Overview The Engineering Unit Editor is used to create and edit the engineering units. The engineering units are not confi...",""],
["../proDASHelp/DASConfigTools/MacroEditor/MacroEditor.htm","Macro Editor","Macro Editor Overview The Macro Editor is used to edit macros that have a Visual Basic Script (VBS) file extension (.vbs). The macros can be execu...",""],
["../proDASHelp/DASConfigTools/PolyEditor/PolyEditor.htm","Polynomial Editor","Polynomial Editor Overview The Polynomial Editor is used to create and edit polynomials, defined by a sequence of float coefficients, to define a ...",""],
["../proDASHelp/DASConfigTools/ScriptEditor/ScriptEditor.htm","Script Editor","Script Editor Overview The Script Editor is used to create and verify the validity of engine test procedures written for proDAS. The Script Editor...",""],
["../proDASHelp/DASConfigTools/SensorEditor/SensorEditor.htm","Sensor Editor","Sensor Editor Overview Expired sensors are reported in the Unified Event Log (UEL) during proDAS startup. proDAS acquires data from thermal, press...",""],
["../proDASHelp/DASConfigTools/TextOutputPages/TextOutputPages.htm","Text Output Pages","Text Output Pages Overview The Text Output Pages is a specialised reporting system within proDAS consisting of pages of preformatted text which co...",""],
["../proDASHelp/DASConfigTools/TransLogDefnEditor/TransLogDefnEditor.htm","Transient Log Definition Editor","Transient Log Definition Editor Overview The Transient Log Definition Editor is used to create and edit the definitions of a transient log. A tran...",""],
["../proDASHelp/DASConfigTools/UserFunctions/UFLanguage.htm","User Function Language","User Function Language Overview The User Function language is separated into the following two sections: Formal Description of Language Detailed D...",""],
["../proDASHelp/DASConfigTools/UserFunctions/UserFunctions.htm","User Functions","User Functions Overview The User Functions System enables a user to define calculations within proDAS, using measured or calculated Real-Time data...",""],
["../proDASHelp/DASSubSysConfig/AFDX/AFDX.htm","AFDX Subsystem Driver (Option*)","AFDX Subsystem Driver (Option*) Overview Avionics Full Duplex Switched Ethernet (ARINC 664 Part 7), or AFDXTM (AFDXTM is a trademark of Airbus), i...",""],
["../proDASHelp/DASSubSysConfig/AllenBradleyPLC/AllenBradleyPLC.htm","Allen Bradley PLC Subsystem","Allen Bradley PLC Subsystem (Option*) Overview The Programmable Logic Controller (PLC), Allen Bradley PLC-5/40E Series, with discrete and analogue...",""],
["../proDASHelp/DASSubSysConfig/ARINC/ARINC.htm","ARINC 429 Subsystem","ARINC 429 Subsystem (Option*) Overview Aeronautical Radio Inc. (ARINC) is a hardware and software standard for engine data collection. Performance...",""],
["../proDASHelp/DASSubSysConfig/ATH/ATH.htm","Ambient Temperature/Humidity (ATH) Subsystem","Ambient Temperature/Humidity (ATH) Subsystem (Option*) Overview The Ambient Temperature and Humidity Subsystem (ATH) interfaces to a number of dif...",""],
["../proDASHelp/DASSubSysConfig/AVM/AVM.html","Aircraft Vibration Monitoring (AVM) Subsystem","Aircraft Vibration Monitoring (AVM) Subsystem (Option*) Overview The Aircraft Vibration Monitoring (AVM) Subsystem monitors vibration from transdu...",""],
["../proDASHelp/DASSubSysConfig/CEC/CEC.htm","CEC Vibration Subsystem","CEC Vibration Subsystem (*Option) Overview The CEC C-CATS 8000 is a modular, programmable vibration signal conditioning system. It accepts inputs ...",""],
["../proDASHelp/DASSubSysConfig/ChannelEditor/ChannelEditor.htm","Channel Editor","Channel Editor Overview proDAS collects and stores engine test data by channels. Each channel has a unique channel name and definition that descri...",""],
["../proDASHelp/DASSubSysConfig/ConfigAdmin/ConfigAdmin.htm","Configuration Administrator","Configuration Administrator Overview The proDAS system is highly flexible and provides the capability to test multiple engine types in endless com...",""],
["../proDASHelp/DASSubSysConfig/ConfigAIs/ConfigAIs.htm","Configuring Analog and Frequency Input Signals","Configuring Analogue and Frequency Input Signals (Option*) Overview The proDAS General Analogue Subsystem VME Extended for Instrumentation (GASSVX...",""],
["../proDASHelp/DASSubSysConfig/ConfigAOs/ConfigAOs.htm","Configuring Analogue Output Signals","Configuring Analogue Output Signals (Option*) Overview The General Analogue Subsystem Analogue Output (GASSAO) hardware comprises one or more E141...",""],
["../proDASHelp/DASSubSysConfig/ConfigCalcChannels/ConfigCalcChannels.htm","Configuring Calculated Channels","Configuring Calculated Channels Overview A Calculated Channel Definition has a specific Equation where computations are performed on data that is ...",""],
["../proDASHelp/DASSubSysConfig/ConfigDIOs/ConfigDIOs.htm","Configuring Digital Input and Output Signals","Configuring Digital Input and Output Signals (Option*) Overview The General Analogue Subsystem Digital Input and Output (GASSDIO) hardware compris...",""],
["../proDASHelp/DASSubSysConfig/ConfigEditors/ConfigEditors.htm","Configuration Editors","Configuration Editors Overview The configuration editors are the user interfaces that allow the operator to setup and control proDAS configuration...",""],
["../proDASHelp/DASSubSysConfig/Consort/Consort.htm","CONSORT Subsystem (Option*)","CONSORT Subsystem (Option*) Overview The proDAS CONSORT Subsystem provides proDAS with steady state data from the PW2000, PW6000 and V2500 engines...",""],
["../proDASHelp/DASSubSysConfig/DDS/DDS.htm","DDS Subsystem (Option*)","DDS Subsystem (Option*) Overview The DDS Subsystem provides the interface to control the following Dynamic Data System (DDS) operations: load and ...",""],
["../proDASHelp/DASSubSysConfig/DDTC/DDTC.htm","Dynamic Data Telemetry Control (DDTC) Subsystem","Dynamic Data Telemetry Control (DDTC) Subsystem (Option*) Overview The DDTC Subsystem driver provides functions to open and close the communicatio...",""],
["../proDASHelp/DASSubSysConfig/DPS/DPS.htm","DSA Pressure Scanner (DPS) Subsystem","DSA Pressure Scanner (DPS) Subsystem (Option*) Overview The DSA Pressure Scanner (DPS) Subsystem is used for pneumatic pressure measurements from ...",""],
["../proDASHelp/DASSubSysConfig/DTCI/DTCI.htm","DTCI Subsystem","DTCI (Option*) Overview The DTC Initium (DTCI) subsystem converts pneumatic pressure measurements and engineering units. The Converted measurement...",""],
["../proDASHelp/DASSubSysConfig/DTS3250/DTS3250.htm","DTS3250 Subsystem (Option*)","DTS3250 Subsystem (Option*) Overview The Digital Thermocouple Scanner DTS3250 Subsystem is used to communicate with the DTS3250 and DTS4050 famili...",""],
["../proDASHelp/DASSubSysConfig/ExternalHooks/ExternalHooks.htm","External Hooks Subsystem","External Hooks Subsystem (Option*) Overview The External Hooks subsystem provides a method of accessing data from the proDAS current value table (...",""],
["../proDASHelp/DASSubSysConfig/FTOTS/FTOTS.htm","Fast Temperature Only Telemetry System (FTOTS) Subsystem","Fast Temperature Only Telemetry System (FTOTS) Subsystem (Option*) Overview The Fast Temperature Only Telemetry System (FTOTS) Subsystem Driver is...",""],
["../proDASHelp/DASSubSysConfig/GEFanucFCS/GEFanucFCS.htm","Generic PLC Subsystem","Generic PLC Subsystem (Option*) Overview The Programmable Logic Controller (PLC), with discrete and analogue input/output modules, controls and mo...",""],
["../proDASHelp/DASSubSysConfig/HighSpeedVXI/HighSpeedVXI.htm","High Speed VXI (HSV) Subsystem","High Speed VXI (HSV) Subsystem (Option*) Overview The High Speed VXI (HSV) Subsystem enables the acquisition and storage of high-speed data (up to...",""],
["../proDASHelp/DASSubSysConfig/M1553/M1553.htm","MIL-1553B Subsystem","M1553 Subsystem Driver (Option*) Overview The M1553 Subsystem Driver is a set of subsystem specific functions used by proDAS to control the Ballar...",""],
["../proDASHelp/DASSubSysConfig/MechScanivalve/MechScanivalve.htm","Mechanical Scanivalve Subsystem (MSS)","Mechanical Scanivalve Subsystem (MSS) (Option*) Overview The Mechanical Scanivalve Subsystem (MSS) provides dry pressure measurements, using the M...",""],
["../proDASHelp/DASSubSysConfig/Modbus/Modbus.htm","Generic Modbus Subsystem Drivers","Generic Modbus Subsystem Drivers (Option*) Overview Modbus is an industry standard for communications. In a Modbus network, all communications are...",""],
["../proDASHelp/DASSubSysConfig/OMRONPLC/OMRONPLC.htm","OMRON PLC Subsystem","OMRON PLC Subsystem (Option*) Overview The OMRON PLC Subsystem communicates with the OMRON C200H PLC System through a RS232 serial connection to g...",""],
["../proDASHelp/DASSubSysConfig/OPC/OPC.htm","OMRON PLC Subsystem (Option*)","OMRON PLC Subsystem (Option*) Overview The OLE for Process Control (OPC) Subsystem is a set of subsystem specific functions used by proDAS to comm...",""],
["../proDASHelp/DASSubSysConfig/PressureBricks/PressureBricks.htm","Pressure Brick Subsystem (PBS)","Pressure Brick Subsystem (PBS) (Option*) Overview The pressure brick subsystem measures transient and steady-state data, providing digitized, temp...",""],
["../proDASHelp/DASSubSysConfig/proDAQ/proDAQ.htm","ProDAQ VXI Subsystem (Option*)","ProDAQ VXI Subsystem (Option*) Overview The ProDAQ VXI subsystem is a data acquisition front end system that uses PCI Express VXIbus to communicat...",""],
["../proDASHelp/DASSubSysConfig/PWM/PWM.htm","Process Write Monitoring (PWM) Subsystem","Process Write Monitoring (PWM) Subsystem (Option*) Overview The Process Write Monitoring (PWM) Subsystem is a software driver that communicates wi...",""],
["../proDASHelp/DASSubSysConfig/RTPDriver/RTPDriver.htm","RTP 2000 Subsystem","RTP 2000 Subsystem (Option*) Overview The Real Time Products (RTP) Subsystem is a set of functions that proDAS uses to exchange data with an RTP c...",""],
["../proDASHelp/DASSubSysConfig/ScanivalveHyscan/ScanivalveHyscan.htm","Scanivalve HyScan Subsystem","Scanivalve HyScan Subsystem (Option*) Overview The Scanivalve HyScan Subsystem is a pressure measurement system. When the Scanivalve Hyscan channe...",""],
["../proDASHelp/DASSubSysConfig/SCUTR/SCUTR.html","Scanning Uniform Temperature Reference (SCUTR) Subsystem","Scanning Uniform Temperature Reference (SCUTR) Subsystem (Option*) Overview The SCanning Uniform Temperature Reference (SCUTR) Subsystem provides ...",""],
["../proDASHelp/DASSubSysConfig/SubsystemEditor/SubsystemEditor.htm","Subsystem Editor","Subsystem Editor Overview The Subsystem Editor is the graphical user interface used to create and edit the subsystem data in the Configuration Dat...",""],
["../proDASHelp/DASSubSysConfig/TBDAU/TBDAU.htm","Test Bed Data Acquistion Unit (TBDAU) Subsystem","Test Bed Data Acquisition Unit (TBDAU) Subsystem (Option*) Overview The Test Bed Data Acquisition Unit (TBDAU) Subsystem is an interface between t...",""],
["../proDASHelp/DASSubSysConfig/TDM/TDM.htm","Telemetry Data Monitoring (TDM) Subsystem","Time Division Multiplexing (TDM) Subsystem (Option*) Overview The Time Division Multiplexing (TDM) Subsystem acquires, processes, stores and distr...",""],
["../proDASHelp/DASSubSysConfig/THG/THG.htm","Thrust Generic (THG) Subsystem (Option*)","Thrust Generic (THG) Subsystem (Option*) Overview The Thrust Generic (THG) Subsystem is a set of functions used by proDAS to perform thrust measur...",""],
["../proDASHelp/DASSubSysConfig/ThrustMeasure/ThrustMeasure.htm","Thrust Measurement Subsystem","Thrust Measurement Subsystem (Option*) Overview The Thrust Measurement Subsystem measures, in one axis, the force exerted on the thrust frame duri...",""],
["../proDASHelp/DASSubSysConfig/TruTemp/TruTemp.htm","TruTemp Temperature Measurement Subsystem - Overview","TruTemp Temperature Measurement Subsystem (Option*) Overview The TruTemp Temperature Measurement Subsystem measures the thermocouple (T/C) input v...",""],
["../proDASHelp/DASSubSysConfig/TSM/TSM.htm","Temperature Scanner Module (TSM) Subsystem","Temperature Scanner Module (TSM) Subsystem (Option*) Overview The TSM Subsystem provides digitized temperature data (in Engineering Units) from th...",""],
["../proDASHelp/DASSubSysConfig/UTRH/UTRH.htm","UTR Half Box (UTRH) Subsystem (Option*)","UTR Half Box (UTRH) Subsystem (Option*) Overview The UTRH Subsystem provides proDAS with cold junction reference temperatures that are measured wi...",""],
["../proDASHelp/DASSubSysConfig/VEXA/VEXA.htm","VTI EX10xxA (VEXA) Subsystem (Option*)","VTI EX10xxA (VEXA) Subsystem (Option*) Overview The VTI EX10xxA (VEXA) Subsystem is used to communicate with the VTI EX10xxA family of products us...",""],
["../proDASHelp/Home/GetStarted/GetStarted.htm","Getting Started","Getting Started Overview The proDAS Integrated Help is a web based user friendly support package offering concise and informative data supported b...",""],
["../proDASHelp/Home/HelpTools/HelpTools.htm","Online Help Tools (OHT)","Online Help Tools (OHT) Overview The content of the Online Help Tools (OHT) is created and maintained by the users of the system and is not a part...",""],
["../proDASHelp/Home/Home.html","Project Title","ProDAS Integrated Help Overview The proDAS Integrated Help is a web based, user friendly support package offering concise and informative data sup...",""],
["../proDASHelp/index.html","PSM78006.2985 - proDAS Integrated Help","PSM78006.2985 - proDAS Integrated Help Release 4.1 January 2020 Home Getting Started Overview Using proDAS Integrated Help Nav Menu NavMenu Main C...",""],
["../proDASHelp/OnlineHelpTools.htm","No title","User Defined Help The online help tools are disabled at this time. Welcome to the User Defined Help. Use the pull down menu to select a specific h...",""],
["../proDASHelp/References/Glossary.html","Acronyms, Abbreviations &#38; Definition of Terms","Acronyms and Abbreviations Abbreviation Acronym ARINC Aeronautical Radio Inc. ASCII American Standard Code for Information Interchange ATH Ambient...",""],
["../proDASHelp/References/HowTos/ClearBrowser.html","How To  Clear your Browser History","How To Clear your Browser History This How To provides the steps required to clear the History from the Google Chrome browser. If the PSM is being...",""],
["../proDASHelp/References/ICDs.html","Interface Control Documents (ICD&#39;s)","Interface Control Documents (ICD&#39;s) The following table is a list of proDAS Interfact Control Documents. Click the document number below to view t...",""],
["../proDASHelp/References/TraceUtility/TraceUtility.html","proDAS Trace Utility","proDAS Trace Utility Overview The trace utility logs informational messages to a trace file that can be used to troubleshoot problems encountered....",""],
["../proDASHelp/References/UsingReferences.htm","Using References","Overview The proDAS Integrated Help contains the following on-line reference information: an Acronyms and Abbreviations list containing the defini...",""],
["../proDASHelp/Search/search.html","No title","Search for: Enter one or more keywords to search for using the Zoom Search Engine. Note that &#39;*&#39; and &#39;?&#39; wildcards are supported. You must have Ja...",""],
["../proDASHelp/StandardTools/AlarmsWarnings/AlarmsWarnings.htm","Alarms and Warnings","Alarms and Warnings Overview During an engine test, the operator is notified, by an Alarm or Warning, when the value of a channel being scanned is...",""],
["../proDASHelp/StandardTools/CalibrateChannels/CalibrateChannels.htm","Calibrating Channels","Calibrating Channels Overview Analogue channels are calibrated by injecting simulated signals from a calibrated source. A variety of techniques ar...",""],
["../proDASHelp/StandardTools/ChanNameSearch/ChanNameSearch.htm","Channel Name Search (CNS)","Channel Name Search (CNS) Overview The Channel Name Search (CNS) is a stand-alone application for searching references of channels in the XML conf...",""],
["../proDASHelp/StandardTools/ContinuousPrinting/ContinuousPrinting.htm","Continuous Printing","Continuous Printing Overview The Print Server is a server program for printing text and graphics. It receives input from other proDAS programs and...",""],
["../proDASHelp/StandardTools/FormatControl/FormatControl.htm","Format Controls","Format Controls Overview Format Controls allow the user to set up the display formats of different data types. The format controls consist of: Flo...",""],
["../proDASHelp/StandardTools/OfflineReviewEventLogs/OfflineReviewEventLogs.htm","Off-line Review of Event Logs","Off-line Review of Unified Event Logs Overview The proDAS Unified Event Log (UEL) tracks all the events that occur while proDAS is running. All me...",""],
["../proDASHelp/StandardTools/RAVE/RAVE.htm","Building Reports with RAVE","Reporting and Viewing Environment (RAVE) Overview The Reporting and Viewing Environment (RAVE) is an application used to view data recorded during...",""],
["../proDASHelp/StandardTools/Replay/Replay.html","Replay Control","Replay Control Overview The Replay Control Graphical User Interface (GUI) is a VCR-style control panel that allows the user to control the Replay ...",""],
["../proDASHelp/StandardTools/SetupDataRecording/SetupDataRecording.htm","Setup Data Recording","Setup Data Recording Overview proDAS records and processes test data for later analysis. This module provides useful information and setup procedu...",""],
["../proDASHelp/StandardTools/TabChanDisplay/TabChanDisplay.htm","Tabular Channel Display (TCD)","Tabular Channel Display (TCD) Overview Tabular Channel Display (TCD) is a stand-alone application used to display online-values of channels in a t...",""],
["../proDASHelp/StandardTools/TAU/TAU.htm","Test Archive Utility (TAU)","Test Archive Utility (TAU) Overview The Test Archive Utility (TAU) is a part of the proDAS system that allows the test cell operator to effectivel...",""],
["../proDASHelp/StandardTools/TRSCDB/TRSCDB.htm","Test Results and Sensor Calibration Database (TRSCDB)","Test Results and Sensor Calibration Database (TRSCDB) Overview The Test Results and Sensor Calibration Database (TRSCDB) contains configuration in...",""],
["../proDASHelp/StandardTools/USS/USS.htm","User Security System (USS)","User Security System (USS) Overview proDAS controls access to each of the proDAS applications via the User Security System (USS), ensuring that on...",""],
["../proDASHelp/TestwithDAS/IntrotoproDAS/IntrotoproDAS.htm","Introduction to proDAS","Introduction to proDAS Overview proDAS is a state-of-the-art, high-performance, Real-Time data acquisition, control, and analysis system that meet...",""],
["../proDASHelp/TestwithDAS/MGTGUI/MGTGUI.htm","Management GUI","Management GUI Overview The Management GUI is the main interface between the user and the proDAS system, providing a user-friendly interface to co...",""],
["../proDASHelp/TestwithDAS/RunEngineTest/RunEngineTest.htm","Running an Engine Test","Running an Engine Test Overview This module is designed to be used as a reference guide in the everyday work of the test cell operator. The differ...",""],
["../proDASHelp/TestwithDAS/StartConfigStopDAS/StartConfigStopDAS.htm","Starting, Configuring &#38; Stopping proDAS","Starting, Configuring and Stopping proDAS Overview The proDAS system must be started in a specific order. The proDAS Real-Time Engine (RTE), execu...",""],
["../proDASHelp/TestwithDAS/ViewEngTestData/ViewEngTestData.htm","Viewing Engine Test Data","Viewing Engine Test Data Overview proDAS enables engine test data to be displayed, printed, and played back through the use of the Reporting and V...",""],
["../proDASHwCfg/AIs/AIDwgs.html","Analogue Inputs - Drawings","Analogue Inputs Engineering Drawings The following table contains links to the MDS engineering drawings for the Analogue Inputs: Drawing Number Dr...",""],
["../proDASHwCfg/AIs/AIOverview.html","Analogue Inputs - Overview","Analogue Inputs Overview Analogue Inputs measure various analogue voltage and current signals originating from the engine and facility systems. Tr...",""],
["../proDASHwCfg/DIOs/DIOComp.html","Digital I/O - Components","Digital Inputs/Outputs Components The Digital Input/Output System contains the following major components: Component Description Opto 22 IDC5D - O...",""],
["../proDASHwCfg/DIOs/DIODwgs.html","Digital Inputs/Outputs - Drawings","Digital Inputs/Outputs Engineering Drawings The following table contains links to the MDS engineering drawings for the Digital Inputs/Outputs Syst...",""],
["../proDASHwCfg/DIOs/DIOOverview.html","Digital Inputs/Outputs - Overview","Digital Inputs/Outputs Overview Digital Input/Outputs transmit and receive facility and engine control signals from devices such as limit switches...",""],
["../proDASHwCfg/DIOs/DIORSPL.html","Digital Inputs/Outputs - RSPL","Digital Inputs/Outputs Recommended Spare Parts List The following table lists the MDS recommended spare parts for the Digital Inputs/Outputs Syste...",""],
["../proDASHwCfg/DIOs/DIOVDocs.html","Digital Inputs/Outputs - Vendor Docs","Digital Inputs/Outputs Vendor Documentation The following table contains links to vendor documentation for components used in the Digital Inputs/ ...",""],
["../proDASHwCfg/Power/PowerComp.html","Power Supplies - Components","Power Supplies (DC) Components The following table contains information on the power supplies used for the components mounted in the equipment rac...",""],
["../proDASHwCfg/Power/PowerDwgs.html","Power Supplies - Drawings","Power Supplies (DC) Engineering Drawings The following table contains links to the MDS engineering drawings for the Power Supplies (DC): Drawing N...",""],
["../proDASHwCfg/Power/PowerMaint.html","Power Supplies - Maintenance","Power Supplies (DC) Maintenance There is no MDS recommended maintenance for the Power Supplies (DC). For details on cleaning the power supplies an...",""],
["../proDASHwCfg/Power/PowerOverview.html","Power Supplies - Overview","Power Supplies (DC) Overview The power supply equipment provides DC power to the components that are mounted in the equipment racks, in the test f...",""],
["../proDASHwCfg/Power/PowerRSPL.html","Power Supplies - RSPL","Power Supplies (DC) Recommended Spare Parts List The following table lists the MDS recommended spare parts for the Power Supplies (DC): Manufactur...",""],
["../proDASHwCfg/Power/PowerVDocs.html","Power Supplies - Vendor Docs","Power Supplies (DC) Vendor Documentation The following table contains links to vendor documentation for the Power Supplies (DC): Manufacturer Manu...",""],
["../proDASHwCfg/Racks/RacksDwgs.html","Equipment Racks - Drawings","Equipment Racks Engineering Drawings The following table contains links to the MDS engineering drawings for the Equipment Racks: Drawing Number Dr...",""],
["../proDASHwCfg/Racks/RacksMaint.html","Equipment Racks - Maintenance","Equipment Racks Maintenance To avoid electric shock, disconnect power from the racks until the dusting and inspection are completed. Electrostatic...",""],
["../proDASHwCfg/Racks/RacksOper.html","Equipment Racks - Operation","Equipment Racks Operation There are four (4) Equipment Racks installed in this facility, labelled CM1 to CM4. See the drawings listed in the table...",""],
["../proDASHwCfg/Racks/RacksOverview.html","Equipment Racks - Overview","Equipment Racks Overview The equipment racks house instrumentation, monitoring, and control equipment. The equipment racks are typically located i...",""],
["../proDASHwCfg/Racks/RacksRSPL.html","Equipment Racks - RSPL","Equipment Racks Recommended Spare Parts List The following table lists the MDS recommended spare parts for the Equipment Racks: Manufacturer Quant...",""],
["../proDASHwCfg/VXI/VXIComp.html","VXI Hardware Components","VXI Hardware Interface Components The VXI System consists of a VXI chassis which contains various plug-in cards. The VXI System is located in the ...",""],
["../proDASHwCfg/VXI/VXIDwgs.html","VXI Hardware Interface - Drawings","VXI Hardware Interface Engineering Drawings The following table contains links to the MDS engineering drawings for the VXI Hardware Interface Syst...",""],
["../proDASHwCfg/VXI/VXIMaint.html","VXI Hardware Interface - Maintenance","VXI Hardware Interface Maintenance To avoid electric shock, power down the VXI chassis prior to performing any maintenance to the VXI system and w...",""],
["../proDASHwCfg/VXI/VXIOper.html","VXI Hardware Interface - Operation","VXI Hardware Interface Operation The following table contains links to instructional information for the VXI Hardware Interface system: Topic How ...",""],
["../proDASHwCfg/VXI/VXIOverview.html","VXI Hardware Interface - Overview","VXI Hardware Interface Overview The VME Extended for Instrumentation (VXI) Hardware Interfaces convert analogue signals from engine or facility tr...",""],
["../proDASHwCfg/VXI/VXIRSPL.html","VXI Hardware Interface - RSPL","VXI Hardware Interface Recommended Spare Parts List The following table lists the MDS recommended spare parts for the VXI Hardware Interface Syste...",""],
["../proDASHwCfg/VXI/VXIVDocs.html","VXI Hardware Interface - Vendor Documentation","VXI Hardware Interface Vendor Documentation The following table contains links to vendor documentation for components used in the VXI Hardware Int...",""],
["../References/Calibration.html","Calibration Instructions","Calibration Instructions Overview Sample calibration of proDAS instructions are available for the following: Environmental Measurement System Fuel...",""],
["../References/Drawings.html","Engineering Drawings","Engineering Drawings A list of applicable engineering drawings is provided for each subsystem. The sheet numbers for each drawing are hyperlinked ...",""],
["../References/GenHealthSafety/GenHealthSafety.html","General Health and Safety","General Health and Safety Overview This section contains general facility health and safety cautions and warnings for the prevention of injury and...",""],
["../References/Glossary.html","Acronyms, Abbreviations &#38; Definition of Terms","Acronyms and Abbreviations Abbreviation Acronym A ampere AC alternating current a/d analogue-to-digital ATH Ambient Temperature / Humidity bar(g) ...",""],
["../References/HowTos/CompCfgHT/DataBackup/HTStartAcronis.html","How To  Start Acronis Backup and Recovery Advanced Workstation with Universal Restore from Windows","How To Start Acronis Backup and Recovery Advanced Workstation with Universal Restore from Windows This How To provides the steps required to start...",""],
["../References/HowTos/CompCfgHT/DataBackup/LinuxAcronisBootMedia.html","HOw To  Create a Bootable Media for Acronis True Image Echo Server","How To Create a Bootable Media for Acronis True Image Echo Server This How To provides the steps required to create a bootable media for Acronis T...",""],
["../References/HowTos/CompCfgHT/DataBackup/LinuxDataBU.html","How To  Turn  On the Configuration Computer","How To Perform Data Backups on the Linux Host Computer This How To provides the steps required to perform data backup on the Linux Host Computer. ",""],
["../References/HowTos/CompCfgHT/DataBackup/LinuxDataRecovery.html","How To  Recover Data on the Linux Host Computer","How To Recover Data on the Linux Host Computer This How To provides the steps required to perform data recovery on the Linux Host Computer. Recove...",""],
["../References/HowTos/CompCfgHT/DataBackup/LinuxDisasterRecovery.html","How To  Perform a Crash Recoveryon the Linux Host Computer","How To Perform a Crash Recovery on the Linux Host Computer This How To provides the steps required to perform a crash recovery on the Linux Host C...",""],
["../References/HowTos/CompCfgHT/DataBackup/LinuxDiskRecovery.html","How To  Restore an Entire Disk Partition","How To Restore an Entire Disk Partition That Does Not Contain the Operating System This How To provides the steps required to restore an entire di...",""],
["../References/HowTos/CompCfgHT/DataBackup/LinuxNASDrive.html","How To  Mount a NAS (Network Attached Storage)","How To Mount a NAS (Network Attached Storage) This How To provides the required steps to mount a NAS. To Mount a NAS to the Linus Host Computer RT...",""],
["../References/HowTos/CompCfgHT/DataBackup/LinuxNASDriveUnMnt.html","How To  Safely Disconnect a NAS (Network Attached Storage)","How To Safely Disconnect a NAS (Network Attached Storage) This How To provides the required steps to disconnect a NAS from the Linux Host Computer...",""],
["../References/HowTos/CompCfgHT/DataBackup/ReviewAcronisLogFiles.html","How To  Review Acronis Log Files","How To Review Acronis Log Files This How To provides the steps required to review the Acronis log files on any of the Windows based computers. Log...",""],
["../References/HowTos/CompCfgHT/DataBackup/USBDrive.html","How To  Safely Connect and Disconnect a USB Drive","How To Safely Connect and Disconnect a USB Drive This How To provides the steps required to safely connect and disconnect a USB Drive to a compute...",""],
["../References/HowTos/CompCfgHT/DataBackup/USBDriveLinux.html","How To  Safely Mount and Disconnect a USB Drive - Linux","How To Safely Mount and Disconnect a USB Drive on the Linux Host Computer This How To provides the steps required to safely connect and disconnect...",""],
["../References/HowTos/CompCfgHT/DataBackup/WindowsCancelDataBU.html","How To  Cancel Data Backup","How To Cancel a Data Backup This How To provides the steps required to cancel the data backup process on a Windows based computer. Acronis Backup ...",""],
["../References/HowTos/CompCfgHT/DataBackup/WindowsDataRecoveryMount.html","How To  Recover Data on a Windows Computer","How To Recover Data on a Windows based Computer by Mounting an Image This How To provides the steps required to perform data recovery on a Windows...",""],
["../References/HowTos/CompCfgHT/DataBackup/WindowsDisasterRecovery.html","How To  Recover Data from an Operating System or Hard Drive Failure on a Windows Based Computer","How To Recover Data from an Operating System or Hard Drive Failure on a Windows Based Computer This How To provides the steps required to perform ...",""],
["../References/HowTos/CompCfgHT/DataBackup/WindowsReviewBUTasks.html","How To  Review Scheduled Tasks in the Acronis Backup &#38; Recovery Application","How To Review Scheduled Tasks in the Acronis Backup &#38; Recovery Application This How To provides the steps required to review the scheduled tasks i...",""],
["../References/HowTos/CompCfgHT/GenInfo/ChangePasswordWindowsPC.html","How To  Change a User Password in Windows","How To Change a User Password in Windows This How To provides the steps required to change a user password on a computer that is runnining a Windo...",""],
["../References/HowTos/CompCfgHT/GenInfo/DustInspectPC.html","How To  Dust and Verify Internal Components","How To Dust and Inspect the Internal Components on a Computer This How To provides the steps required to dust and inspect the computer&#39;s internal ...",""],
["../References/HowTos/CompCfgHT/GenInfo/RecoverSysErr.html","How To  Recover from a System Error","How To Recover from a System Error This How To provides the steps required to recover from a system error on a computer running a Windows operatin...",""],
["../References/HowTos/CompCfgHT/GenInfo/RestartWindowsPC.html","How To  Restart a Windows Based Computer","How To Restart a Windows Based Computer This How To provides the steps required to restart a computer that is running a Windows operating system. ...",""],
["../References/HowTos/CompCfgHT/GenInfo/ReviewWindowsLogFiles.html","How To  Review Windows Log Files","How To Review Windows Log Files This How To provides the steps required to review the System Log, Application Log and Security Log files on any of...",""],
["../References/HowTos/CompCfgHT/GenInfo/ScanHDPC.html","How To  Scan the Hard Drive","How To Scan the Hard Drive for Errors This How To provides the steps required to scan and verify the computer&#39;s hard drive. You can solve some com...",""],
["../References/HowTos/CompCfgHT/GenInfo/SubnetMaskGateway.html","How To  Obtain the Subnet Mask and Default Gateway","How To Obtain the Subnet Mask and Default Gateway This How To provides the required steps to obtain the subnet mask and default gateway on a Windo...",""],
["../References/HowTos/CompCfgHT/GenInfo/TurnOffPC.html","How To  Turn  On the Configuration Computer","How To Turn Off a Windows Based Computer This How To provides the steps required to turn off a computer that is running a Windows operating system...",""],
["../References/HowTos/CompCfgHT/GenInfo/TurnOnWindowsPC.html","How To  Power Up the Computer","How To Power Up the Computer This How To provides the steps required to power up a computer that is running a Windows operating system. To Power U...",""],
["../References/HowTos/CompCfgHT/HostPCHT/ChangeUserModeHostPC.html","How To  Change the User Mode","How To Change the User Mode This How To provides the steps required to change the user mode to Multi-User Mode and Single User Mode. To Change to ...",""],
["../References/HowTos/CompCfgHT/HostPCHT/CheckDiskSpaceHostPC.html","How To  Check the Disk Space on the Host Computer","How To Check the Disk Space on the Host Computer This How To provides the steps required to check the disk space on the Host Computer. To Check th...",""],
["../References/HowTos/CompCfgHT/HostPCHT/LogOnHostPC.html","How To  Log On to the Host Computer","How To Log In to the Host Computer This How To provides the steps required to log in to the Host Computer. To Log In to the Host Computer Turn on ...",""],
["../References/HowTos/CompCfgHT/HostPCHT/MngUserAcountsHostPC.html","How To  Add, Remove, or Modify User Accounts","How To Add, Remove, or Modify User Accounts This How To provides the steps required to Add, Remove, or Modify User Accounts using the Host Compute...",""],
["../References/HowTos/CompCfgHT/HostPCHT/MonitorHDDHostPC.html","How To  Monitor Disks on the Running Host Computer","How To Monitor Disks on the Running Host Computer This How To provides the steps required to monitor the hard disk drives on the Host Computer. Mo...",""],
["../References/HowTos/CompCfgHT/HostPCHT/RebootHostPC.html","How To  Reboot the Host Computer","How To Reboot the Host Computer This How To provides the steps required to reboot the Host Computer. To Reboot the Host Computer The Host Computer...",""],
["../References/HowTos/CompCfgHT/HostPCHT/StartHostPC.html","How To  Start the Host Computer","How To Turn On the Host Computer This How To provides the steps required to turn on the Host Computer. To prevent loss of data or damage to compon...",""],
["../References/HowTos/CompCfgHT/HostPCHT/StartproDASHW.html","How To  Turn On the proDAS Computers","How To Turn On the proDAS Computers This How To provides the steps required to turn on the proDAS computers. The proDAS computers must be turned o...",""],
["../References/HowTos/CompCfgHT/HostPCHT/SwitchHostPC.html","How To  Switch to the Spare Host Computer (If Available)","How To Switch to the Spare Host Computer (If Available) This How To provides the steps required to switch to a spare Host Computer if one is avail...",""],
["../References/HowTos/CompCfgHT/HostPCHT/TroubleShootHostPC.html","Linux Host Computer- Troubleshooting","Troubleshooting This section provides common troubleshooting steps for the Host Computer. It contains procedures for: If the Host Computer Freezes...",""],
["../References/HowTos/CompCfgHT/HostPCHT/TurnOffHostPC.html","How To  Turn Off the Host Computer","How To Turn Off the Host Computer This How To provides the steps required to turn off the Host Computer. The Host Computer is turned off only for ...",""],
["../References/HowTos/CompCfgHT/MgmtGUIHT/RestartMgmtPC.html","How To  Restart the Management GUI Computer","How To Restart the Management GUI Computer This How To provides the steps required to restart the Management GUI Computer using the Windows taskba...",""],
["../References/HowTos/CompCfgHT/MgmtGUIHT/StartMmgtGUI.html","How To  Start the proDAS Management GUI Application","How To Start the proDAS Management GUI Application This How To provides the steps required to start the proDAS Management GUI application on the M...",""],
["../References/HowTos/CompCfgHT/MgmtGUIHT/TurnOffMgmtPC.html","How To  Power Down the Management GUI Computer","How To Power Down the Management GUI Computer from the Windows Taskbar This How To provides the steps required to power down off the Management GU...",""],
["../References/HowTos/CompCfgHT/RTDPCHT/OPCConnect.html","How To  Turn Off the Real-Time Display Computer","How To Set Up the Bridge Software to Connect to the OPC Server This How To provides the steps required to set up the bridge software to connect to...",""],
["../References/HowTos/CompCfgHT/RTDPCHT/RestartRTDPC.html","How To  Restart a Real-Time Display Computer","How To Restart a Real-Time Display Computer This How To provides the steps required to restart a Real-Time Display Computer. proDAS must be reconf...",""],
["../References/HowTos/CompCfgHT/RTDPCHT/TurnOffRTD.html","How To  Turn Off the Real-Time Display Computer","How To Power Down the Real-Time Display Computer from the Windows Taskbar This How To provides the steps required to turn off the Real-Time Displa...",""],
["../References/HowTos/ControlMon/UECU/ActuatorWiring.html","How To  Check the Actuator Enclosure Assembly","How To Check the Actuator Enclosure Assembly This How To provides the steps required to check the screws, fasteners, and wiring in the Actuator En...",""],
["../References/HowTos/ControlMon/UECU/AdjustOverride.html","How To  Adjust the Actuator Override Stop Position","How To Adjust the Actuator Override Stop Position This How To provides the steps required to adjust the actuator override stop position. The Throt...",""],
["../References/HowTos/ControlMon/UECU/AirMotor.html","How To  Lubricate the Air Motor","How To Lubricate the Air Motor This How To provides the steps required to lubricate the air motor. The Throttle components are under power. To avo...",""],
["../References/HowTos/ControlMon/UECU/CalibrateActuator.html","How To  Calibrate the Actuator","How To Calibrate the Actuator This How To provides the steps required to calibrate the actuator. The Throttle components are under power. To avoid...",""],
["../References/HowTos/ControlMon/UECU/CalibrateChannel.html","How To  Calibrate a Channel","How To Calibrate a Channel This How To provides the steps required to calibrate a channel. All analogue input channels must be calibrated to conve...",""],
["../References/HowTos/ControlMon/UECU/CalibrateLever.html","How To  Calibrate the Throttle Lever","How To Calibrate the Throttle Lever This How To provides the steps required to calibrate the throttle lever. The Throttle components are under pow...",""],
["../References/HowTos/ControlMon/UECU/CheckThrottleWiring.html","How To  Check the Throttle Quadrant Wiring","How To Check the Throttle Quadrant Wiring This How To provides the steps required to check the throttle quadrant wiring. The Throttle components a...",""],
["../References/HowTos/ControlMon/UECU/CleanThrottleQuad.html","How To  Clean the Throttle Quadrant","How To Clean the Throttle Quadrant This How To provides the steps required to clean the throttle quadrant. The Throttle components are under power...",""],
["../References/HowTos/ControlMon/UECU/Configuration.html","How To  Modify the Configuration Files","Reference Configuration Files This section contains information on the configuration files used by the Throttle System. Only operators familiar wi...",""],
["../References/HowTos/ControlMon/UECU/DaisyChainResolver.html","How To  Daisy Chain the Controller, RDVT and Resolver Chassis","How To Daisy Chain the Controller, RDVT and Resolver Chassis This How To provides the steps and information required to daisy chain the controller...",""],
["../References/HowTos/ControlMon/UECU/InspectBrushes.html","How To  Inspect the Brushes on the Throttle Lever","How To Inspect the Brushes on the Throttle Lever This How To provides the steps required to inspect the brushes on the throttle lever. The Throttl...",""],
["../References/HowTos/ControlMon/UECU/RigActuator.html","How To  Rig an Actuator","How To Rig an Actuator This How To provides the steps required to rig an actuator. Rigging is the process used to relate the position of the fuel ...",""],
["../References/HowTos/ControlMon/UECU/RunModeAuto.html","How To  Run an Engine in Run Mode (Auto)","How To Run an Engine in Run Mode (Auto) This How To provides the steps and information required to run an engine in Auto Throttle Mode. Running an...",""],
["../References/HowTos/ControlMon/UECU/RunModeManual.html","How To  Run an Engine in Run Mode (Manual)","How To Run an Engine in Run Mode (Manual) This How To provides the steps required to run an engine in Run Mode (Manual). Running an Engine in Run ...",""],
["../References/HowTos/ControlMon/UECU/SelectEngine.html","How To  Select an Engine","How To Select an Engine This How To provides the steps required to select an engine. To Select an Engine Before the Throttle System can be used to...",""],
["../References/HowTos/ControlMon/UECU/SetupLeverPot.html","How To  Set Up the Lever Potentiometer","How To Set Up the Lever Potentiometer This How To provides the steps required to set up the lever potentiometer. The Throttle components are under...",""],
["../References/HowTos/ControlMon/UECU/SpurBacklashGear.html","How To  Check the Actuator Spur and Anti-Backlash Gears","How To Check the Actuator Spur and Anti-Backlash Gears This How To provides the steps required to checking the actuator spur and anti-backlash gea...",""],
["../References/HowTos/ControlMon/UECU/StartUECU500.html","How To  Start the UECU-500 Mark III Throttle","How To Start the UECU-500 Mark III Throttle This How To provides the steps required to start the UECU-500 Mark III Throttle. To Start the UECU-500...",""],
["../References/HowTos/ControlMon/UECU/ThrottleControllerWiring.html","How To  Check the Wiring in the Throttle Controller Enclosure Assembly","How To Check the Wiring in the Throttle Controller Enclosure Assembly This How To provides the steps required to checking the wiring in the thrott...",""],
["../References/HowTos/ControlMon/UECU/TroubleshootResolver.html","How To  Troubleshoot Issues with a Resolver","How To Troubleshoot Issues with a Resolver This How To provides the steps required to troubleshoot issues with a resolver. One of the difficulties...",""],
["../References/HowTos/ControlMon/UECU/UECUBackupRecovery.html","How To  Back up and Recover Data","How To Backup and Recover Data for the UECU-Mark III Throttle System This How To provides information on how to backup and recover data for the UE...",""],
["../References/HowTos/ControlMon/UECU/UECUConnectDAS.html","How To  Connect an Analogue Position Indicator or DAS","How To Connect an Analogue Position Indicator or Data Acquisition System (DAS) The analogue position outputs a +/- 10 VDC signal from a 15 bit dig...",""],
["../References/HowTos/ControlMon/UECU/UECUInstallation.html","How To  Install UECU Mark III","How To Install the UECU-500 Mark III Throttle The UECU-500 Mark III Throttle may be installed in an existing test facility, or incorporated into a...",""],
["../References/HowTos/ControlMon/UECU/UseOverrideSystem.html","How To  Activate and Reset the Override System","How To Activate and Reset the Override System This How To provides the steps and information required to activate and reset the Override system. T...",""],
["../References/HowTos/ControlMon/UECU/VerifyOverride.html","How To  Verify the Actuator Override System Operation","How To Verify the Actuator Override System Operation This How To provides the steps required to verify the actuator override system operation. The...",""],
["../References/HowTos/Home/ClearBrowser.html","How To  Clear your Browser History","How To Clear your Browser History This How To provides the steps required to clear the History from the Google Chrome browser. If the PSM is being...",""],
["../References/HowTos/Measurement/PneuPMeas/AddPressScanner.html","How To  Add a New PBS Pressure Scanner","How To Add a New PBS Pressure Scanner This How To describes the required steps to add a new PBS pressure scanner to the proDAS system. When a new ...",""],
["../References/HowTos/Measurement/PneuPMeas/CfgScanNetParams.html","How To  Configure Network Parameters on a Scanner","How To Configure Network Parameters on a Scanner This How To provides the steps required to configure network parameters on a scanner. To Configur...",""],
["../References/HowTos/Measurement/PneuPMeas/InspectPneuMS.html","How To  Inspect the Pneumatic Pressure Measurement System","How To Inspect the Pneumatic Pressure Measurement System This How To provides the steps required to inspect the Pneumatic Pressure Measurement sys...",""],
["../References/HowTos/Measurement/PneuPMeas/PurgeCal.html","How To   Purge and Calibrate the Pressure Scanning System","How To Purge and Zero the Pressure Scanners This How To provides the steps required to purge and zero the pressure scanners. To Purge and Zero the...",""],
["../References/HowTos/Measurement/PneuPMeas/TroublePressScan.html","How To  Troubleshoot Trigger Problems with Pressure Scanners","How To Troubleshoot Trigger Problems with Pressure Scanners This How To provides the steps required to troubleshoot trigger problems with pressure...",""],
["../References/HowTos/Measurement/TempMeas/AddDTSScanner.html","How To - Add a DTS3250/DTS4050 Temperature Scanner","How To - Add a DTS3250/DTS4050 Temperature Scanner This How To describes the required steps to add a DTS3250/DTS4050 temperature scanner to the pr...",""],
["../References/HowTos/Measurement/TempMeas/AddEX10xxAScanner.html","How To - Add a EX10xxA Temperature Scanner","How To - Add an EX10xxA Temperature Scanner This How To describes the required steps to add an EX10xxA temperature scanner to the proDAS system. W...",""],
["../References/HowTos/Measurement/TempMeas/ConfigDTSScanner.html","How To - Configure a DTS3250/DTS4050 Temperature Scanner","How To - Configure a DTS3250/DTS4050 Temperature Scanner This How To describes the steps required to configure a DTS3250/DTS4050 temperature scann...",""],
["../References/HowTos/Measurement/TempMeas/ConfigE10xxAScanner.html","How To - Configure an EX1048A Temperature Scanner","How To - Configure an EX1048A Temperature Scanner This How To describes the required steps to properly configure an EX1048A temperature scanner. T...",""],
["../References/HowTos/Measurement/TempMeas/InspectCalTempMS.html","How To   Inspect the Temperature Measurement System","How To Inspect the Calibration of a Temperature Scanner This How To provides the steps required to inspect the calibration of a temperature scanne...",""],
["../References/HowTos/Measurement/TempMeas/InspectTempMS.html","How To  Inspect the Temperature Measurement System","How To Inspect the Temperature Measurement System This How To provides the steps required to inspect the Temperature Measurement System. To Inspec...",""],
["../References/HowTos/Measurement/TempMeas/TroubleTempScan.html","How To  Troubleshoot Trigger Problems with Pressure Scanners","How To Troubleshoot Trigger Problems with DTS3250/DTS4050 Temperature Scanners This How To provides the steps required to troubleshoot trigger pro...",""],
["../References/HowTos/proDAS/InstrPowerDown.html","How To  Power Down the Instrumentation System","How To Power Down the Instrumentation System This How To provides the steps required to perform a complete power down of the instrumentation. The ...",""],
["../References/HowTos/proDAS/InstrPowerUp.html","How To  Power Up the Instrumentation System","How To Power Up the Instrumentation System This How To provides the steps required to perform a complete power up of the instrumentation. A comple...",""],
["../References/HowTos/proDASHw/AIs/VerifyAnalogCurrentChannel.html","How to Verify an Analogue Current Channel of the Fuel Measurement System","How To Verify an Analogue Current Channel This How To provides the steps required to verify an analogue current channel. This How To applies to th...",""],
["../References/HowTos/proDASHw/AIs/VerifyAnalogVoltageChannel.html","How to Verify an Analogue Voltage Channel of the Fuel Measurement System","How To Verify an Analogue Voltage Channel This How To provides the steps required to verify an analogue voltage channel. This How To applies to th...",""],
["../References/HowTos/proDASHw/Racks/InspectRacks.html","How To  Inspect the Equipment Racks","How To Inspect the Equipment Racks This How To provides the steps required to inspect the equipment racks. To Inspect the Equipment Racks To avoid...",""],
["../References/HowTos/proDASHw/VXI/ChangeCardVXI.html","How To  Replace a VXI Card in the VXI Chassis","How To Replace a VXI Card in the VXI Chassis This How To provides the steps required to replace a VXI card in the VXI chassis. The modular design ...",""],
["../References/HowTos/proDASHw/VXI/ExternalRefSignal.html","How To  Check the Operation of the VXI DIO Card","How To Check the Operation of the VXI DIO Card This How To provides the steps required to verify the operation of the VXI digital input/output car...",""],
["../References/HowTos/proDASHw/VXI/InspectCleanVXI.html","No title","How To Inspect and Clean the VXI Chassis This How To provides the steps required to inspect and clean the VXI Chassis. To Inspect and Clean the VX...",""],
["../References/Maintenance.html","Maintenance","Maintenance Schedule The system maintenance tables below contain the maintenance schedule for each system. The schedule indicates the frequency re...",""],
["../References/RSPLs.html","Recommended Spare Parts List","Recommended Spare Parts List To reduce down time, it is recommended that a spare parts inventory be maintained for each subsystem. The Recommended...",""],
["../References/Terms.html","Definition of Terms","Definition of Terms Term Definition (Items in bold type are also defined in the table) Action An action defines the RTE automatic response when th...",""],
["../References/UsingReferences.htm","Using References","Using the References Overview The References section contains the following on-line reference information: an Acronyms and Abbreviations list cont...",""],
["../References/VendorDocs/MeasurementSpecialties/nussuman/nussindx.htm","NetScanner&#8482; Unified Startup Software (NUSS) User&#39;s Manual","NetScanner Unified Startup Software (NUSS) User&#39;s Manual (pdf format) Preface, Table of Contents, Chapter 1 - Overview Chapter 2 - Installation an...",""],
["../References/VendorDocs.html","Vendor Documentation","Vendor Documentation Servicing and troubleshooting information for items that are not produced by MDS may be found in the vendor documentation (or...",""],
["../Search/search.html","No title","Search for: Enter one or more keywords to search for using the Zoom Search Engine. Note that &#39;*&#39; and &#39;?&#39; wildcards are supported. You must have Ja...",""]];
