pageinfo = [[1580159054,0,0,0,null],
	[1580159090,0,0,0,null],
	[1580159115,0,0,0,null],
	[1580159136,0,0,0,null],
	[1580159178,0,0,0,null],
	[1580159248,0,0,0,null],
	[1580159336,0,0,0,null],
	[1580159396,0,0,0,null],
	[1580161295,0,0,0,null],
	[1580330105,0,0,0,null],
	[1580161471,0,0,0,null],
	[1580159756,0,0,0,null],
	[1580329943,0,0,0,null],
	[1580159854,0,0,0,null],
	[1580159890,0,0,0,null],
	[1580159984,0,0,0,null],
	[1580161295,0,0,0,null],
	[1580330320,0,0,0,null],
	[1580161293,0,0,0,null],
	[1580160265,0,0,0,null],
	[1580160355,0,0,0,null],
	[1580327570,0,0,0,null],
	[1580242888,0,0,0,null],
	[1580160469,0,0,0,null],
	[1580327644,0,0,0,null],
	[1580312074,0,0,0,null],
	[1580329411,0,0,0,null],
	[1580329134,0,0,0,null],
	[1579786810,0,0,0,null],
	[1580160808,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580139388,0,0,0,null],
	[1580327041,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580161307,0,0,0,null],
	[1580328892,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580150522,0,0,0,null],
	[1580150548,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580239643,0,0,0,null],
	[1580394202,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580394690,0,0,0,null],
	[1580394798,0,0,0,null],
	[1580394590,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580394913,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580395075,0,0,0,null],
	[1580397076,0,0,0,null],
	[1580161295,0,0,0,null],
	[1580161295,0,0,0,null],
	[1580161295,0,0,0,null],
	[1580161295,0,0,0,null],
	[1580155307,0,0,0,null],
	[1580155335,0,0,0,null],
	[1580136806,0,0,0,null],
	[1580312077,0,0,0,null],
	[1580320758,0,0,0,null],
	[1580155511,0,0,0,null],
	[1580326565,0,0,0,null],
	[1580155482,0,0,0,null],
	[1580155429,0,0,0,null],
	[1580155453,0,0,0,null],
	[1461095743,0,0,0,null],
	[1580156654,0,0,0,null],
	[1580157190,0,0,0,null],
	[1580156685,0,0,0,null],
	[1580395565,0,0,0,null],
	[1580156856,0,0,0,null],
	[1580135107,0,0,0,null],
	[1580157503,0,0,0,null],
	[1580156892,0,0,0,null],
	[1580396045,0,0,0,null],
	[1580161295,0,0,0,null],
	[1580396226,0,0,0,null],
	[1580397362,0,0,0,null],
	[1580232855,0,0,0,null],
	[1580161294,0,0,0,null],
	[1580302723,0,0,0,null],
	[1580161295,0,0,0,null],
	[1580161295,0,0,0,null],
	[1580156498,0,0,0,null]];
pagedata = [ ["../CustomApps/ACI/ACI.htm","Automated CITS Import into proDAS (Option*)","Automated CITS Import into proDAS (Option*) Overview The Automated CITS Import into proDAS (ACI) utility converts CITS configuration files into th...",""],
["../CustomApps/ArincChanList/ArincChanList.htm","ARINC Channel List (Option*)","ARINC Channel List (Option*) Overview The ARINC Display shows the ARINC information being transmitted to and received from the EEC (Electronic Eng...",""],
["../CustomApps/CCS/CCS.html","CCS Messaging System (Option*)","CCS Messaging System (Option*) Overview The CCS Messaging System is used to exchange messages between proDAS and the CCS (client-supplied). This a...",""],
["../CustomApps/CDS/CDS.htm","Calibration Data Sync (CDS) Utility (Option*)","Calibration Data Sync (CDS) Utility (Option*) Overview The Calibration Data Sync (CDS) Utility synchronizes calibration data tables in the local p...",""],
["../CustomApps/CIE/CIE.htm","Configuration Import / Export (CIE) Utility (Option*)","Configuration Import / Export (CIE) Utility (Option*) Overview The Configuration Import / Export (CIE) Utility allows the user to import Rolls-Roy...",""],
["../CustomApps/CUTI/CUTI.htm","Configure User Test Information (Option*)","Configure User Test Information (Option*) Overview Configuration User Test Information (CUTI) is a single step method of configuring proDAS (inclu...",""],
["../CustomApps/DCU/DCU.htm","Data Conversion Utility (DCU)","Data Conversion Utility (DCU) (Option*) Overview The Data Conversion Utility (DCU) is a Windows based console application which converts Steady-St...",""],
["../CustomApps/Easifit/Easifit.html","EASIFIT","EASIFIT (Option*) Overview EASIFIT is a specific file format that is designed to interface with the Rolls-Royce on-line data analysis programs whi...",""],
["../CustomApps/ExtHookFramework/ExtHookFramework.htm","External Hook Framework (Option*)","External Hook Framework (Option*) Overview The External Hook Framework allows the user to easily read and write channel values from and to the pro...",""],
["../CustomApps/InstrumentControls/InstrumentControls.htm","Instrument Controls (Option*)","Instrument Controls (Option*) Overview Accessed from the Management GUI Tools menu, the proDAS Instrument Controls have been divided into the foll...",""],
["../CustomApps/MDSThrustCalUtility/MDSThrustCalUtility.htm","MDS Thrust Calibration Utility (*Option)","MDS Thrust Calibration Utility (*Option) Overview The MDS Thrust Calibration Utility provides test cell personnel with the ability to calibrate th...",""],
["../CustomApps/OMS/OMS.htm","Onboard Maintenance System (Option*)","Onboard Maintenance System (Option*) Overview The Onboard Maintenance System (OMS) is part of the proDAS ARINC System used to test the FADEC on th...",""],
["../CustomApps/REMS/REMS.html","REMS External Hook Application (Option*)","Richmond Emission Measurement System (REMS) External Hook Application (Option*) Overview The Richmond Emission Measurement System (REMS) External ...",""],
["../CustomApps/RuleEditor/RuleEditor.htm","Rule Editor (Option*)","Rule Editor (Option*) Overview The Rule Editor is a stand-alone application designed to create and edit rules to be used later in the Automated CI...",""],
["../CustomApps/SnecmaXML/SnecmaXML.htm","Snecma XML Transfer (Option*)","Snecma XML Transfer (Option*) Overview The Snecma XML Transfer (SNEXML) application translates steady-state (fullset) and transient (history and c...",""],
["../CustomApps/TCA/TCA.htm","Thrust Calibration Application (TCA)","Thrust Calibration Application (TCA) (Option*) Overview The Thrust Calibration Application (TCA) is a component of the Thrust Calibration and Thru...",""],
["../CustomApps/TOCEUM/TOCEUM.htm","TOCEUM (Option*)","TOCEUM (Option*) Overview The TOC and EUM is an External Hook program that monitors the state of the engine and records statistics, on the life us...",""],
["../CustomApps/TrimBalance/TrimBalance.htm","Engine Trim Balance","Engine Trim Balance (Option*) Overview The Trim Balance system is used in conjunction with the CEC Vibration Monitoring System that addresses engi...",""],
["../CustomApps/WeatherStation/WeatherStation.htm","Weather Station (WS) Subsystem","Weather Station (WS) Subsystem (Option*) Overview The Weather Station (WS) Subsystem is a proDAS external hook program connected to a MET3A/MET4A ...",""],
["../DASConfigTools/BPTableEditor/BPTableEditor.htm","Break Point Table Editor","Break Point Table Editor Overview The Break Point Table Editor is used to create and edit break point tables. Only break point tables used for cal...",""],
["../DASConfigTools/DisplayPages/DisplayPages.htm","Creating and Modifying Display Pages","Creating and Modifying Display Pages Overview Display pages are created, administrated and modified by the RTD Editor and displayed in the RTD Dri...",""],
["../DASConfigTools/EUEditor/EUEditor.htm","Engineering Unit Editor","Engineering Unit Editor Overview The Engineering Unit Editor is used to create and edit the engineering units. The engineering units are not confi...",""],
["../DASConfigTools/MacroEditor/MacroEditor.htm","Macro Editor","Macro Editor Overview The Macro Editor is used to edit macros that have a Visual Basic Script (VBS) file extension (.vbs). The macros can be execu...",""],
["../DASConfigTools/PolyEditor/PolyEditor.htm","Polynomial Editor","Polynomial Editor Overview The Polynomial Editor is used to create and edit polynomials, defined by a sequence of float coefficients, to define a ...",""],
["../DASConfigTools/ScriptEditor/ScriptEditor.htm","Script Editor","Script Editor Overview The Script Editor is used to create and verify the validity of engine test procedures written for proDAS. The Script Editor...",""],
["../DASConfigTools/SensorEditor/SensorEditor.htm","Sensor Editor","Sensor Editor Overview Expired sensors are reported in the Unified Event Log (UEL) during proDAS startup. proDAS acquires data from thermal, press...",""],
["../DASConfigTools/TextOutputPages/TextOutputPages.htm","Text Output Pages","Text Output Pages Overview The Text Output Pages is a specialised reporting system within proDAS consisting of pages of preformatted text which co...",""],
["../DASConfigTools/TransLogDefnEditor/TransLogDefnEditor.htm","Transient Log Definition Editor","Transient Log Definition Editor Overview The Transient Log Definition Editor is used to create and edit the definitions of a transient log. A tran...",""],
["../DASConfigTools/UserFunctions/UFLanguage.htm","User Function Language","User Function Language Overview The User Function language is separated into the following two sections: Formal Description of Language Detailed D...",""],
["../DASConfigTools/UserFunctions/UserFunctions.htm","User Functions","User Functions Overview The User Functions System enables a user to define calculations within proDAS, using measured or calculated Real-Time data...",""],
["../DASSubSysConfig/AFDX/AFDX.htm","AFDX Subsystem Driver (Option*)","AFDX Subsystem Driver (Option*) Overview Avionics Full Duplex Switched Ethernet (ARINC 664 Part 7), or AFDXTM (AFDXTM is a trademark of Airbus), i...",""],
["../DASSubSysConfig/AllenBradleyPLC/AllenBradleyPLC.htm","Allen Bradley PLC Subsystem","Allen Bradley PLC Subsystem (Option*) Overview The Programmable Logic Controller (PLC), Allen Bradley PLC-5/40E Series, with discrete and analogue...",""],
["../DASSubSysConfig/ARINC/ARINC.htm","ARINC 429 Subsystem","ARINC 429 Subsystem (Option*) Overview Aeronautical Radio Inc. (ARINC) is a hardware and software standard for engine data collection. Performance...",""],
["../DASSubSysConfig/ATH/ATH.htm","Ambient Temperature/Humidity (ATH) Subsystem","Ambient Temperature/Humidity (ATH) Subsystem (Option*) Overview The Ambient Temperature and Humidity Subsystem (ATH) interfaces to a number of dif...",""],
["../DASSubSysConfig/AVM/AVM.html","Aircraft Vibration Monitoring (AVM) Subsystem","Aircraft Vibration Monitoring (AVM) Subsystem (Option*) Overview The Aircraft Vibration Monitoring (AVM) Subsystem monitors vibration from transdu...",""],
["../DASSubSysConfig/CEC/CEC.htm","CEC Vibration Subsystem","CEC Vibration Subsystem (*Option) Overview The CEC C-CATS 8000 is a modular, programmable vibration signal conditioning system. It accepts inputs ...",""],
["../DASSubSysConfig/ChannelEditor/ChannelEditor.htm","Channel Editor","Channel Editor Overview proDAS collects and stores engine test data by channels. Each channel has a unique channel name and definition that descri...",""],
["../DASSubSysConfig/ConfigAdmin/ConfigAdmin.htm","Configuration Administrator","Configuration Administrator Overview The proDAS system is highly flexible and provides the capability to test multiple engine types in endless com...",""],
["../DASSubSysConfig/ConfigAIs/ConfigAIs.htm","Configuring Analog and Frequency Input Signals","Configuring Analogue and Frequency Input Signals (Option*) Overview The proDAS General Analogue Subsystem VME Extended for Instrumentation (GASSVX...",""],
["../DASSubSysConfig/ConfigAOs/ConfigAOs.htm","Configuring Analogue Output Signals","Configuring Analogue Output Signals (Option*) Overview The General Analogue Subsystem Analogue Output (GASSAO) hardware comprises one or more E141...",""],
["../DASSubSysConfig/ConfigCalcChannels/ConfigCalcChannels.htm","Configuring Calculated Channels","Configuring Calculated Channels Overview A Calculated Channel Definition has a specific Equation where computations are performed on data that is ...",""],
["../DASSubSysConfig/ConfigDIOs/ConfigDIOs.htm","Configuring Digital Input and Output Signals","Configuring Digital Input and Output Signals (Option*) Overview The General Analogue Subsystem Digital Input and Output (GASSDIO) hardware compris...",""],
["../DASSubSysConfig/ConfigEditors/ConfigEditors.htm","Configuration Editors","Configuration Editors Overview The configuration editors are the user interfaces that allow the operator to setup and control proDAS configuration...",""],
["../DASSubSysConfig/Consort/Consort.htm","CONSORT Subsystem (Option*)","CONSORT Subsystem (Option*) Overview The proDAS CONSORT Subsystem provides proDAS with steady state data from the PW2000, PW6000 and V2500 engines...",""],
["../DASSubSysConfig/DDS/DDS.htm","DDS Subsystem (Option*)","DDS Subsystem (Option*) Overview The DDS Subsystem provides the interface to control the following Dynamic Data System (DDS) operations: load and ...",""],
["../DASSubSysConfig/DDTC/DDTC.htm","Dynamic Data Telemetry Control (DDTC) Subsystem","Dynamic Data Telemetry Control (DDTC) Subsystem (Option*) Overview The DDTC Subsystem driver provides functions to open and close the communicatio...",""],
["../DASSubSysConfig/DPS/DPS.htm","DSA Pressure Scanner (DPS) Subsystem","DSA Pressure Scanner (DPS) Subsystem (Option*) Overview The DSA Pressure Scanner (DPS) Subsystem is used for pneumatic pressure measurements from ...",""],
["../DASSubSysConfig/DTCI/DTCI.htm","DTCI Subsystem","DTCI (Option*) Overview The DTC Initium (DTCI) subsystem converts pneumatic pressure measurements and engineering units. The Converted measurement...",""],
["../DASSubSysConfig/DTS3250/DTS3250.htm","DTS3250 Subsystem (Option*)","DTS3250 Subsystem (Option*) Overview The Digital Thermocouple Scanner DTS3250 Subsystem is used to communicate with the DTS3250 and DTS4050 famili...",""],
["../DASSubSysConfig/ExternalHooks/ExternalHooks.htm","External Hooks Subsystem","External Hooks Subsystem (Option*) Overview The External Hooks subsystem provides a method of accessing data from the proDAS current value table (...",""],
["../DASSubSysConfig/FTOTS/FTOTS.htm","Fast Temperature Only Telemetry System (FTOTS) Subsystem","Fast Temperature Only Telemetry System (FTOTS) Subsystem (Option*) Overview The Fast Temperature Only Telemetry System (FTOTS) Subsystem Driver is...",""],
["../DASSubSysConfig/GEFanucFCS/GEFanucFCS.htm","Generic PLC Subsystem","Generic PLC Subsystem (Option*) Overview The Programmable Logic Controller (PLC), with discrete and analogue input/output modules, controls and mo...",""],
["../DASSubSysConfig/HighSpeedVXI/HighSpeedVXI.htm","High Speed VXI (HSV) Subsystem","High Speed VXI (HSV) Subsystem (Option*) Overview The High Speed VXI (HSV) Subsystem enables the acquisition and storage of high-speed data (up to...",""],
["../DASSubSysConfig/M1553/M1553.htm","MIL-1553B Subsystem","M1553 Subsystem Driver (Option*) Overview The M1553 Subsystem Driver is a set of subsystem specific functions used by proDAS to control the Ballar...",""],
["../DASSubSysConfig/MechScanivalve/MechScanivalve.htm","Mechanical Scanivalve Subsystem (MSS)","Mechanical Scanivalve Subsystem (MSS) (Option*) Overview The Mechanical Scanivalve Subsystem (MSS) provides dry pressure measurements, using the M...",""],
["../DASSubSysConfig/Modbus/Modbus.htm","Generic Modbus Subsystem Drivers","Generic Modbus Subsystem Drivers (Option*) Overview Modbus is an industry standard for communications. In a Modbus network, all communications are...",""],
["../DASSubSysConfig/OMRONPLC/OMRONPLC.htm","OMRON PLC Subsystem","OMRON PLC Subsystem (Option*) Overview The OMRON PLC Subsystem communicates with the OMRON C200H PLC System through a RS232 serial connection to g...",""],
["../DASSubSysConfig/OPC/OPC.htm","OMRON PLC Subsystem (Option*)","OMRON PLC Subsystem (Option*) Overview The OLE for Process Control (OPC) Subsystem is a set of subsystem specific functions used by proDAS to comm...",""],
["../DASSubSysConfig/PressureBricks/PressureBricks.htm","Pressure Brick Subsystem (PBS)","Pressure Brick Subsystem (PBS) (Option*) Overview The pressure brick subsystem measures transient and steady-state data, providing digitized, temp...",""],
["../DASSubSysConfig/proDAQ/proDAQ.htm","ProDAQ VXI Subsystem (Option*)","ProDAQ VXI Subsystem (Option*) Overview The ProDAQ VXI subsystem is a data acquisition front end system that uses PCI Express VXIbus to communicat...",""],
["../DASSubSysConfig/PWM/PWM.htm","Process Write Monitoring (PWM) Subsystem","Process Write Monitoring (PWM) Subsystem (Option*) Overview The Process Write Monitoring (PWM) Subsystem is a software driver that communicates wi...",""],
["../DASSubSysConfig/RTPDriver/RTPDriver.htm","RTP 2000 Subsystem","RTP 2000 Subsystem (Option*) Overview The Real Time Products (RTP) Subsystem is a set of functions that proDAS uses to exchange data with an RTP c...",""],
["../DASSubSysConfig/ScanivalveHyscan/ScanivalveHyscan.htm","Scanivalve HyScan Subsystem","Scanivalve HyScan Subsystem (Option*) Overview The Scanivalve HyScan Subsystem is a pressure measurement system. When the Scanivalve Hyscan channe...",""],
["../DASSubSysConfig/SCUTR/SCUTR.html","Scanning Uniform Temperature Reference (SCUTR) Subsystem","Scanning Uniform Temperature Reference (SCUTR) Subsystem (Option*) Overview The SCanning Uniform Temperature Reference (SCUTR) Subsystem provides ...",""],
["../DASSubSysConfig/SubsystemEditor/SubsystemEditor.htm","Subsystem Editor","Subsystem Editor Overview The Subsystem Editor is the graphical user interface used to create and edit the subsystem data in the Configuration Dat...",""],
["../DASSubSysConfig/TBDAU/TBDAU.htm","Test Bed Data Acquistion Unit (TBDAU) Subsystem","Test Bed Data Acquisition Unit (TBDAU) Subsystem (Option*) Overview The Test Bed Data Acquisition Unit (TBDAU) Subsystem is an interface between t...",""],
["../DASSubSysConfig/TDM/TDM.htm","Telemetry Data Monitoring (TDM) Subsystem","Time Division Multiplexing (TDM) Subsystem (Option*) Overview The Time Division Multiplexing (TDM) Subsystem acquires, processes, stores and distr...",""],
["../DASSubSysConfig/THG/THG.htm","Thrust Generic (THG) Subsystem (Option*)","Thrust Generic (THG) Subsystem (Option*) Overview The Thrust Generic (THG) Subsystem is a set of functions used by proDAS to perform thrust measur...",""],
["../DASSubSysConfig/ThrustMeasure/ThrustMeasure.htm","Thrust Measurement Subsystem","Thrust Measurement Subsystem (Option*) Overview The Thrust Measurement Subsystem measures, in one axis, the force exerted on the thrust frame duri...",""],
["../DASSubSysConfig/TruTemp/TruTemp.htm","TruTemp Temperature Measurement Subsystem - Overview","TruTemp Temperature Measurement Subsystem (Option*) Overview The TruTemp Temperature Measurement Subsystem measures the thermocouple (T/C) input v...",""],
["../DASSubSysConfig/TSM/TSM.htm","Temperature Scanner Module (TSM) Subsystem","Temperature Scanner Module (TSM) Subsystem (Option*) Overview The TSM Subsystem provides digitized temperature data (in Engineering Units) from th...",""],
["../DASSubSysConfig/UTRH/UTRH.htm","UTR Half Box (UTRH) Subsystem (Option*)","UTR Half Box (UTRH) Subsystem (Option*) Overview The UTRH Subsystem provides proDAS with cold junction reference temperatures that are measured wi...",""],
["../DASSubSysConfig/VEXA/VEXA.htm","VTI EX10xxA (VEXA) Subsystem (Option*)","VTI EX10xxA (VEXA) Subsystem (Option*) Overview The VTI EX10xxA (VEXA) Subsystem is used to communicate with the VTI EX10xxA family of products us...",""],
["../Home/GetStarted/GetStarted.htm","Getting Started","Getting Started Overview The proDAS Integrated Help is a web based user friendly support package offering concise and informative data supported b...",""],
["../Home/HelpTools/HelpTools.htm","Online Help Tools (OHT)","Online Help Tools (OHT) Overview The content of the Online Help Tools (OHT) is created and maintained by the users of the system and is not a part...",""],
["../Home/Home.html","Project Title","ProDAS Integrated Help Overview The proDAS Integrated Help is a web based, user friendly support package offering concise and informative data sup...",""],
["../index.html","PSM78006.2985 - proDAS Integrated Help","PSM78006.2985 - proDAS Integrated Help Release 4.1 January 2020 Home Getting Started Overview Using proDAS Integrated Help Nav Menu NavMenu Main C...",""],
["../OnlineHelpTools.htm","No title","User Defined Help The online help tools are disabled at this time. Welcome to the User Defined Help. Use the pull down menu to select a specific h...",""],
["../References/Glossary.html","Acronyms, Abbreviations &#38; Definition of Terms","Acronyms and Abbreviations Abbreviation Acronym ARINC Aeronautical Radio Inc. ASCII American Standard Code for Information Interchange ATH Ambient...",""],
["../References/HowTos/ClearBrowser.html","How To  Clear your Browser History","How To Clear your Browser History This How To provides the steps required to clear the History from the Google Chrome browser. If the PSM is being...",""],
["../References/ICDs.html","Interface Control Documents (ICD&#39;s)","Interface Control Documents (ICD&#39;s) The following table is a list of proDAS Interfact Control Documents. Click the document number below to view t...",""],
["../References/TraceUtility/TraceUtility.html","proDAS Trace Utility","proDAS Trace Utility Overview The trace utility logs informational messages to a trace file that can be used to troubleshoot problems encountered....",""],
["../References/UsingReferences.htm","Using References","Overview The proDAS Integrated Help contains the following on-line reference information: an Acronyms and Abbreviations list containing the defini...",""],
["../Search/search.html","No title","Search for: Enter one or more keywords to search for using the Zoom Search Engine. Note that &#39;*&#39; and &#39;?&#39; wildcards are supported. You must have Ja...",""],
["../StandardTools/AlarmsWarnings/AlarmsWarnings.htm","Alarms and Warnings","Alarms and Warnings Overview During an engine test, the operator is notified, by an Alarm or Warning, when the value of a channel being scanned is...",""],
["../StandardTools/CalibrateChannels/CalibrateChannels.htm","Calibrating Channels","Calibrating Channels Overview Analogue channels are calibrated by injecting simulated signals from a calibrated source. A variety of techniques ar...",""],
["../StandardTools/ChanNameSearch/ChanNameSearch.htm","Channel Name Search (CNS)","Channel Name Search (CNS) Overview The Channel Name Search (CNS) is a stand-alone application for searching references of channels in the XML conf...",""],
["../StandardTools/ContinuousPrinting/ContinuousPrinting.htm","Continuous Printing","Continuous Printing Overview The Print Server is a server program for printing text and graphics. It receives input from other proDAS programs and...",""],
["../StandardTools/FormatControl/FormatControl.htm","Format Controls","Format Controls Overview Format Controls allow the user to set up the display formats of different data types. The format controls consist of: Flo...",""],
["../StandardTools/OfflineReviewEventLogs/OfflineReviewEventLogs.htm","Off-line Review of Event Logs","Off-line Review of Unified Event Logs Overview The proDAS Unified Event Log (UEL) tracks all the events that occur while proDAS is running. All me...",""],
["../StandardTools/RAVE/RAVE.htm","Building Reports with RAVE","Reporting and Viewing Environment (RAVE) Overview The Reporting and Viewing Environment (RAVE) is an application used to view data recorded during...",""],
["../StandardTools/Replay/Replay.html","Replay Control","Replay Control Overview The Replay Control Graphical User Interface (GUI) is a VCR-style control panel that allows the user to control the Replay ...",""],
["../StandardTools/SetupDataRecording/SetupDataRecording.htm","Setup Data Recording","Setup Data Recording Overview proDAS records and processes test data for later analysis. This module provides useful information and setup procedu...",""],
["../StandardTools/TabChanDisplay/TabChanDisplay.htm","Tabular Channel Display (TCD)","Tabular Channel Display (TCD) Overview Tabular Channel Display (TCD) is a stand-alone application used to display online-values of channels in a t...",""],
["../StandardTools/TAU/TAU.htm","Test Archive Utility (TAU)","Test Archive Utility (TAU) Overview The Test Archive Utility (TAU) is a part of the proDAS system that allows the test cell operator to effectivel...",""],
["../StandardTools/TRSCDB/TRSCDB.htm","Test Results and Sensor Calibration Database (TRSCDB)","Test Results and Sensor Calibration Database (TRSCDB) Overview The Test Results and Sensor Calibration Database (TRSCDB) contains configuration in...",""],
["../StandardTools/USS/USS.htm","User Security System (USS)","User Security System (USS) Overview proDAS controls access to each of the proDAS applications via the User Security System (USS), ensuring that on...",""],
["../TestwithDAS/IntrotoproDAS/IntrotoproDAS.htm","Introduction to proDAS","Introduction to proDAS Overview proDAS is a state-of-the-art, high-performance, Real-Time data acquisition, control, and analysis system that meet...",""],
["../TestwithDAS/MGTGUI/MGTGUI.htm","Management GUI","Management GUI Overview The Management GUI is the main interface between the user and the proDAS system, providing a user-friendly interface to co...",""],
["../TestwithDAS/RunEngineTest/RunEngineTest.htm","Running an Engine Test","Running an Engine Test Overview This module is designed to be used as a reference guide in the everyday work of the test cell operator. The differ...",""],
["../TestwithDAS/StartConfigStopDAS/StartConfigStopDAS.htm","Starting, Configuring &#38; Stopping proDAS","Starting, Configuring and Stopping proDAS Overview The proDAS system must be started in a specific order. The proDAS Real-Time Engine (RTE), execu...",""],
["../TestwithDAS/ViewEngTestData/ViewEngTestData.htm","Viewing Engine Test Data","Viewing Engine Test Data Overview proDAS enables engine test data to be displayed, printed, and played back through the use of the Reporting and V...",""]];
